### ISSUE TITLE
Относно тестовете

### ISSUE THREAD

**Issue by chaneto** [luchob/softuni-sept-2021-misc#100]
Пак съм аз и то през почивния ден, малко неудобно.
Имам питане относно тестовете.
Значи когато ги ръннвам един по един минават всички, обаче когато ги рънна най отгоре където е класа където всички се ръннват един по един автоматично не минават?
Досещам се защо, но кое е правилното от двете, един по един или?
Всъщност не знам как ще ги проверяват?

**Comment by luchob** [comment]
Здрасти!

Един по един не е правилното :-) Трябва да може да се пуснат всички заедно и да нямаш никаква гаранция кой минава преди или след кой. 

Не ти минават, защото имаш интеграционен тест, който остава нещо в базата и чупи другия. Това трябва да се оправи.

Поздрави,
Л.
