### ISSUE TITLE
Относно Heroku

### ISSUE THREAD

**Issue by VaskoVasilevv** [luchob/softuni-sept-2021-misc#101]
Здравей Лъчо, след като паря стъпка по стъпка както е описано в лекцията ми излиза следната грешка:
java.lang.RuntimeException: Driver org.postgresql.Driver claims to not accept jdbcUrl, ${JDBC_DATABASE_URL}

**Comment by luchob** [comment]
Здрасти, Васко!

Това означава, че не ти подава environment variable JDBC_DATABASE_URL. Което пък означава, че не си добавил както трябва heroku postgresql add on. Провери дали е така, допускам че нещо си объркал на тази стъпка. Например, ако погледнеш в UI-a на херокуто, вътре в детайлите на апа ти, трябва да се вижда инсталиран този add on. Ако го няма, няма да инициализира променливата и ще получиш точно този ексепшън.

Поздрави,
Л.

**Comment by VaskoVasilevv** [comment]
Има инсталиран add on, но то и самия ап не тръгва в IntelliJ

**Comment by luchob** [comment]
Здравей! 

Току що ти направих 1 форк на репозиторито и се опитах да деплойна. Наистина не може, защото съдържанието на Procfile е грешно. Трябва да е:

```
web: java -jar target/CarDealer-0.0.1-SNAPSHOT.jar
``` 

Това е заради `pom.xml`:

```
    <artifactId>CarDealer</artifactId>
    <version>0.0.1-SNAPSHOT</version>
```

После, трябва да е инсталиран add on на heroku postgresql както е показано на следващата снимка:

<img width="616" alt="Screenshot 2021-12-04 at 20 37 29" src="https://user-images.githubusercontent.com/10339738/144720817-2881bd3b-5bd6-4470-90b7-499362cdca07.png">

След това пак не тръгва, защото няма CLOUDINARY_SECRET :-) Ако добавя някакъв dummy сикрет, напр:

<img width="1226" alt="Screenshot 2021-12-04 at 20 38 49" src="https://user-images.githubusercontent.com/10339738/144720862-7ce9ec16-11e4-4f55-98d2-2a33cb0e2016.png">

Ако разреша и това - появява се в хероку, показвам:

<img width="826" alt="Screenshot 2021-12-04 at 20 40 50" src="https://user-images.githubusercontent.com/10339738/144720909-36113d09-2564-40e5-935f-bfe1d1e3fbd7.png">

Сега ще я изтрия обаче, но мисля, че вече ти си на ход :-)

Поздрави,
Л.

**Comment by VaskoVasilevv** [comment]
Благодаря много 🙂
