### ISSUE TITLE
Малко въпросче за съвет

### ISSUE THREAD

**Issue by HristoManov91** [luchob/softuni-sept-2021-misc#102]
Здравей Лъчо.Имам едно малко въпросче понеже в UserController-a в много от заявките имам разни колекции да кажем от имената на User-ите.Чудех не е ли по-добре да изкарам в статична променлива такава колекция и само да я подавам където трябва или @ModelAttribute анотацията да използвам да я подготвя предварително и пак да я подавам където трябва или да си остава извикването на метода във всяка заявка където ми трябва.Ако може да ме посъветваш как е по-добре.Благодаря :)

**Comment by luchob** [comment]
Привет!

Може ли един по-конкретен пример за такава колекция от `UserController`?

Поздрави,
Л.

**Comment by HristoManov91** [comment]
userService.findAllUsersFullName()

**Comment by luchob** [comment]
Привет!

В случая не е особено уместно да ползваш ModelAttribute, тъй като колекцията не ти трябва абсолютно навсякъде (има само три извиквания) и по този начин ще направиш излишна заявка. Статична променлива също не можеш да направиш, тъй като стойността на колекцията се променя по време на изпълнението на програмата, т.е. не може да я кешираш.

Според мен си е ок както е сега. Като гледам проекта - време е за тестове :-)

Поздрави и усмихната неделя!

Л.

**Comment by HristoManov91** [comment]
Да сега ги почвам и тях и heroku после.А дали може да погледнеш в
consultants add sale не ми изкарва съобщенията за грешките на полетата и не
мога да разбера защо ?

На нд, 5.12.2021 г., 16:14 Lachezar Balev ***@***.***> написа:
