### ISSUE TITLE
Integration test :  constraint [null]; ConstraintViolationException: could not execute statement

### ISSUE THREAD

**Issue by yavorhr** [luchob/softuni-sept-2021-misc#103]
Здрасти, Лъчо!
имам проблем при Integration test за добавяне на обект (addDog). 
Мисля, че тестът ми гърми, тъй като след създаването на dog в DogServiceImpl, създавам Picture Entity, в което set-вам релация към кучето (в Picture Entity си пазя всички снимки за кучетата).
Въпросът ми е как след като взема параметрите с mockMvc.perform(post("/dogs/add"), да симулирам релация с Picture Entity, за да не ми гърми тестът с Null pointer (предполагам, че грешката идва от там).

Тестът ми се казва DogsControllerTest : https://github.com/yavorhr/adoptDontShop

Благодаря ти отново за отделеното време !
Поздрави,
Явор

**Comment by yavorhr** [comment]
Оправих се някак! Блъскане му е майката с тези тестове, само това помага, голяма гадост са!

Поздрави и хубав следобед,
Явор

**Comment by luchob** [comment]
Блъскане му е майката, така е и копане надълбоко :-) Аз например прекопах цялата градина на селото и също като теб съм доволен :-)

<img width="502" alt="Screenshot 2021-12-05 at 15 35 59" src="https://user-images.githubusercontent.com/10339738/144748786-8e076484-feea-4bfc-8f7a-e6b863f7f7f9.png">
