### ISSUE TITLE
Счупен тест и data.sql

### ISSUE THREAD

**Issue by apostol03** [luchob/softuni-sept-2021-misc#104]
Извинявай много, че пускам въпрос след края на курса, но имам нужда от друг поглед над проблемите, които получавам.
1. Когато използвам data.sql със sql.init always, въпреки defer.datasource.initialization=true, пак се получава SQLSyntaxError. Като рънна приложението и после пусна и sql-a върви безпроблемно - та това е единия проблем, търсил съм сигурно общо към 2 часа - нищо...
2. Когато пусна теста testRegisterUser сам си бачка, но когато пусна всички тестове само той гърми с NullPointerException - предполагам нещо от setup-ите в някой beforeEach(), но така и не открих откъде е проблемът. 
Благодаря ти отново за всичко!

Линк към проекта -> https://github.com/apostol03/Tunes_R_Us

**Comment by luchob** [comment]
Привет! Понеже е динамичен следобяда, първо ще ти пиша за проблем но. 1. 

Не се оправя заради коментарите :-) Ако разгледаш ексепшъна, се опитва да изпълни:

```
# ARTISTS INSERT INTO artists(id, bio, name) VALUES
```

Коментар в SQL се пише ей така:

```
-- ARTISTS
INSERT INTO artists(id, bio, name)
```

Яд ли те е? :-)))

**Comment by apostol03** [comment]
Хахаха, моляяя. Яд ме е да. Верно от това беше проблема... Благодаря ти много.

**Comment by luchob** [comment]
Относно въпрос 2. Когато пуснеш всички тестове, те споделят един контекст и една база, съответно. В `AdminControllerTest`, **който минава първи** имаш следния код:

```
    @AfterEach
    void tearDown() {
        userRepository.deleteAll();
    }
```

А гърмящия ти тест вика `UserServiceImpl` в който пък има следния код:

```
 UserRole userRole = userRoleRepository.findByRole(UserRoleEnum.USER);
     ...
        newUser
        ....
                .setRoles(List.of(userRole));
```

:-) Сега пак те е яд сигурно :-))

Поздрави,
Л.

**Comment by apostol03** [comment]
Мхм, мхм. Отново си прав. Благодаря ти отново.
