### ISSUE TITLE
Java Web Final Project

### ISSUE THREAD

**Issue by kcdimov** [luchob/softuni-sept-2021-misc#105]
Здравей, 
напралил съм проект библиотека за филми. Идеята е потребителят с права админ да може да добавя филми, актьори, в същото време другите потребители ще могат да добавят снимки и ревюта на филмите. 

Но не ми се зареждат формите за добавяне и също не работи и самото добавяне. Вече няколко дни се опитвам да намеря решение, но не мога да разбера какъв е проблема. 

https://github.com/kcdimov/Java-Web-Project

Проекта е в зип файл, понеже не съм работил досега с GitHub и ще ми е необходимо малко време да намеря под Линукс  как да ги запиша в репозиторито. 

Благодаря предварително.
Костадин

**Comment by luchob** [comment]
Добра вечер!

Причината се корени в грешно инициализираните роли. Ето какво имаш в таблицата `authorities`.
<img width="1067" alt="Screenshot 2021-12-06 at 19 19 41" src="https://user-images.githubusercontent.com/10339738/144892109-89fab86b-2216-4a26-87e3-10e0e6985603.png">

Това е странно, защото стойностите трябва да са ADMIN и USER, например. Проблемът е още в ентитито:


```
@Entity
@Table(name = "authorities")
public class Authority extends BaseEntity{
....
    @Column
    @NotNull
    public SimpleGrantedAuthority getName() {
        return name;
    }
```

Това нещо тук трябва да е String или Enum. Виж как е направено в mobilele, няма нищо по-различно.

Поздрави,
Л.
