### ISSUE TITLE
Heroku Maven issue

### ISSUE THREAD

**Issue by Alexander-Gruev** [luchob/softuni-sept-2021-misc#107]
Здравей Лъчо, имам следния проблем при опит за деплоймент в Heroku (Ползвах метода през GitHub):
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project Fitshop: Fatal error compiling: invalid target release: 11 

Имам файл system.properties с java.runtime.version=11, в pom.xml имам <java.version>11</java.version> , но очевидно не е достатъчно. Нищо от Stackoverflow не помага също, ще се радвам ако имаш идеи

https://github.com/Alexander-Gruev/Fitshop-Heroku

**Comment by luchob** [comment]
Привет!

Мии.... направих Форк на проекта ти в моят акаунт и когато се опитвам да го кача, барабар с env variables за клаудинари няма проблем, това ми е лога:

```
-----> Building on the Heroku-20 stack
-----> Using buildpack: heroku/java
-----> Java app detected
-----> Installing JDK 11... done
-----> Executing Maven
       $ ./mvnw -DskipTests clean dependency:list install
       [INFO] Scanning for projects...
       [INFO] 
       [INFO] ------------------------< com.example:Fitshop >-------------------------
       [INFO] Building Fitshop 0.0.1-SNAPSHOT
       [INFO] --------------------------------[ jar ]---------------------------------
       [INFO] 
       [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ Fitshop ---
       [INFO] 
       [INFO] --- maven-dependency-plugin:3.1.2:list (default-cli) @ Fitshop ---
       [INFO] 
       [INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ Fitshop ---
       [INFO] Using 'UTF-8' encoding to copy filtered resources.
       [INFO] Using 'UTF-8' encoding to copy filtered properties files.
       [INFO] Copying 1 resource
       [INFO] Copying 32 resources
       [INFO] 
       [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ Fitshop ---
       [INFO] Changes detected - recompiling the module!
       [INFO] Compiling 66 source files to /tmp/build_b1f0c33b/target/classes
       [INFO] 
       [INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ Fitshop ---
       [INFO] Using 'UTF-8' encoding to copy filtered resources.
       [INFO] Using 'UTF-8' encoding to copy filtered properties files.
       [INFO] Copying 1 resource
       [INFO] 
       [INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ Fitshop ---
       [INFO] Changes detected - recompiling the module!
       [INFO] Compiling 8 source files to /tmp/build_b1f0c33b/target/test-classes
       [INFO] 
       [INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ Fitshop ---
       [INFO] Tests are skipped.
       [INFO] 
       [INFO] --- maven-jar-plugin:3.2.0:jar (default-jar) @ Fitshop ---
       [INFO] Building jar: /tmp/build_b1f0c33b/target/Fitshop-0.0.1-SNAPSHOT.jar
       [INFO] 
       [INFO] --- spring-boot-maven-plugin:2.5.6:repackage (repackage) @ Fitshop ---
       [INFO] Replacing main artifact with repackaged archive
       [INFO] 
       [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ Fitshop ---
       [INFO] Installing /tmp/build_b1f0c33b/target/Fitshop-0.0.1-SNAPSHOT.jar to /tmp/codon/tmp/cache/.m2/repository/com/example/Fitshop/0.0.1-SNAPSHOT/Fitshop-0.0.1-SNAPSHOT.jar
       [INFO] Installing /tmp/build_b1f0c33b/pom.xml to /tmp/codon/tmp/cache/.m2/repository/com/example/Fitshop/0.0.1-SNAPSHOT/Fitshop-0.0.1-SNAPSHOT.pom
       [INFO] ------------------------------------------------------------------------
       [INFO] BUILD SUCCESS
       [INFO] ------------------------------------------------------------------------
       [INFO] Total time:  6.846 s
       [INFO] Finished at: 2021-12-06T20:05:36Z
       [INFO] ------------------------------------------------------------------------
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 105.6M
-----> Launching...
       Released v9
       https://alex11111.herokuapp.com/ deployed to Heroku
```

Всичко тръгва, но фронтенда не се отваря:

<img width="1045" alt="Screenshot 2021-12-06 at 22 09 50" src="https://user-images.githubusercontent.com/10339738/144915214-7e1355b7-63bf-49e1-8a28-baaf5e479483.png">

Проблемът гози път е:


```
2021-12-06T20:06:28.935566+00:00 app[web.1]: 2021-12-06 20:06:28.934 ERROR 4 --- [io-27255-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException: Unable to access lob stream; nested exception is org.hibernate.HibernateException: Unable to access lob stream] with root cause
2021-12-06T20:06:28.935568+00:00 app[web.1]: 
2021-12-06T20:06:28.935569+00:00 app[web.1]: org.postgresql.util.PSQLException: Large Objects may not be used in auto-commit mode.
2021-12-06T20:06:28.935571+00:00 app[web.1]: 	at org.postgresql.largeobject.LargeObjectManager.open(LargeObjectManager.java:243) ~[postgresql-42.2.24.jar!/:42.2.24]
2021-12-06T20:06:28.935571+00:00 app[web.1]: 	at org.postgresql.largeobject.LargeObjectManager.open(LargeObjectManager.java:229) ~[postgresql-42.2.24.jar!/:42.2.24]
2021-12-06T20
```

Т.е. въобще не ми мяза на java 11 :-)

Л.

**Comment by Alexander-Gruev** [comment]
Не разбирам защо на мен ми дава грешката за Java версията - някъде използвам грешно jdk или?

**Comment by Alexander-Gruev** [comment]
Благодаря ти, махнах @Lob и се оправи.

**Comment by Alexander-Gruev** [comment]
Тоест проблемът е от @Lob анотацията - аз имам такава на description в ProductEntity, но когато я махна на мястото на description на някой продук в приложението ми излиза рандъм числото 385515396

**Comment by Alexander-Gruev** [comment]
Също така не разбирам кога промените в кода се отразяват на деплоя в Heroku като не използвам Heroku CLI, а графичния интерфейс - задал съм му enable automatic deploys. Това би трябвало да означава, че всеки push към master ще направи нов деплой, нали така?

**Comment by luchob** [comment]
Проблемът с lob е с postge шитница. Накратко казано, въпросните large обекти (допускам става тип TEXT) може да се пазят в няколко полета и затова си иска transactional анотация. В нета ако се зачетеш неминуемо ще попаднеш на [това](https://github.com/jhipster/generator-jhipster/issues/8146), където се споменават няколко решенийца:

 * Mark the repository @transactional : I don't like it very much, because that gives more work to the service layer (which has to join the transaction, etc). So there's a little performance hit, for nothing much.
 * Mark the REST endpoint with @transactional(readOnly=true) : I don't like having transactions in the view layer. There's one added benefit from the point above: you can mark your transaction as readonly, so you have a performance gain.
 * Configure the connection pool to have autocommit = false. In fact, I thought we were already doing that, as the (older) connections pools I used were doing this. But that's not the case with HikariCP!!

Разгледай го и ако не можеш да го подкараш пиши :-)

**Comment by Alexander-Gruev** [comment]
Сработи с @Transactional на репото, благодаря ти за отделеното време!

**Comment by luchob** [comment]
Юху 🎉
