### ISSUE TITLE
Am I testing my layers correctly?

### ISSUE THREAD

**Issue by AlexanderNestorov** [luchob/softuni-sept-2021-misc#109]
Здравейте, написал съм Integration тестове за контролерите и Unit тестове за репозиторита-та и сървисите по следния начин:

https://github.com/AlexanderNestorov/PC-Point/tree/master/src/test/java/com/example/pcpoint

Въпросът ми е дали тестовете отговарят на изискванията за технологии и покритие?

**Comment by luchob** [comment]
Здравей!

Това не е чист Unit тест:

```
@SpringBootTest
@AutoConfigureTestDatabase(connection = EmbeddedDatabaseConnection.H2)
public class LocationServiceTest 
```

Това е интегрейшън тест, тъй като вдига контекста на спринг и създава in memory база и т.н. 

Относно репозиторитата, подобни тестове също не са ок:
```
 @Test
    @DisplayName("Testing if get method returns correct amount of locations")
    public void testGetAllMethod() {
        assertThat(locationRepository.findAll().size()).isEqualTo(2);
    }
```

Те реално тестват дали Spring Data работи правилно, а не дали твоя код работи или не. Защото в репозиторито няма твой код. Такова нещо може да направиш евентуално ако имаш `Query` анотации.

За покритието не съм сигурен, тъй като като ги пуснах фейлнаха 76 теста...

Поздрави,
Л.
