### ISSUE TITLE
NullPointerException на инджектнати сървиси в контролера след @PreAuthorize

### ISSUE THREAD

**Issue by amdimov** [luchob/softuni-sept-2021-misc#110]
Здравейте,

Пак ударих на Спринг мотичката, макар че може и аз да съм нея в случая :D

Ако може да ми помогнете, когато имате време за следния въпрос:

Имам UserController за профил на юзър, който през профила пуска поръчка през форма. Админът я разглежда и връща оферта. 

В UserController има @PreAuthorize, който проверява дали номерът на поръчката е на съответния юзър.
```
@PreAuthorize("@ordersServiceImpl.isOwner(#principal.name, #id)")
@GetMapping("/profile/order/{id}")
```
...

Когато правя: `@GetMapping("/profile/invoice/{invoiceNumber}")`
всички инджектнати сървиси излизат null - [снимка](https://res.cloudinary.com/dronasqsi/image/upload/v1639062885/vqjpafc58atdhc4dfnli.png) и грешка 500.

Предполатам, че е свързано с Proxy, което разглеждахме на лекцията при проблема с кеширането,
но се чудя ако как би могъл да се оправи в този случай.

GIT-https://github.com/amdimov/print-shop-exam.git

Благодаря,
Александър

**Comment by amdimov** [comment]
Много ме е яд за изгубеното време в търсене на грешката, защото решението на проблема е много скучно.
Направил съм @GetMapping метода в контролера private...

NPE на всички депендънси се получаваше само когато юзърът се опита да достъпи фактурата по номер -  `@GetMapping("/profile/invoice/{invoiceNumber}")` т.е. когато удря private метода в UserController  :-)

Благодаря, че се отзовахте и съжалявам, че ви ангажирах  с въпрос от недоглеждане.

**Comment by luchob** [comment]
Хаха, супер! Дааа... това и аз съм го настъпвал веднъж преди време, докато се усетя беше голям фън :-)

Радвам се, че почваш сам да ги откриваш, това си е вече напредък :-)

Лека и полека!
