### ISSUE TITLE
Problem with Heroku

### ISSUE THREAD

**Issue by StoqnBorislavov** [luchob/softuni-sept-2021-misc#111]
Здравей Лъчо,
Имам много странен проблем с деплойнатото приложение в Heroku. 
Локално всичко работи нормално, но в Хероку статистиките които пресмятам с интерсептор ми гърмят с 500.
Пътя за статистиките е : /admin/statistics.
Като паролата на потребителя е 1234 с име stoyan.
https://gentle-temple-45146.herokuapp.com/
Това е линка от Хероку.
https://github.com/StoqnBorislavov/FuelLogg
Това е репото.
Благодаря за отделеното време.

**Comment by luchob** [comment]
Здравей!

Когато ти деплойнах апп-а с fork (и настроих POSTGRE променливите :-) ) статистиките работят.

<img width="1022" alt="Screenshot 2021-12-12 at 8 33 09" src="https://user-images.githubusercontent.com/10339738/145702926-9d9f0f8f-28ad-433d-ae56-e957bda0ac89.png">

За да разберем какъв е проблема при теб, трябва да видим ексепшъна, заради който става 500. Той е наличен в логовете. Ако ползваш heroku CLI командата е:

```
heroku logs -a <името_на_app-a> --tail
```

При деплой от UI-a:

<img width="276" alt="Screenshot 2021-12-12 at 8 34 53" src="https://user-images.githubusercontent.com/10339738/145702971-054a9e63-766a-4be9-a672-66984640a43d.png">

Погледни ги и извади ексепшъна, за да видим какъв е проблема.  :-)

Поздрави,
Л.

**Comment by StoqnBorislavov** [comment]
Здравей,
Благодаря ти за отговора.
Всъщност аз спрях проверката за най голямото време за лог през последните
24 часа тъй като го хванах че там гърми.
Според мен е нещо свързано с Instant времето и ми връщаше NullPointer.
Но така и не открих от какво е точно тъй като не мога да видя точно как се
записват записите в базата на Heroku.
Поздрави!
На нд, 12.12.2021 г., 8:36 Lachezar Balev ***@***.***> написа:

**Comment by luchob** [comment]
Ами... трябва stack trace иначе... :-)

**Comment by StoqnBorislavov** [comment]
Дано изпитващите са по снисходителни.
Благодаря за знанието което ни предаде.
Успех и може да се засичаме за напред в средите.
Приятна почивка.
Поздрави!

На нд, 12.12.2021 г., 8:43 Lachezar Balev ***@***.***> написа:
