### ISSUE TITLE
Проблем с логин

### ISSUE THREAD

**Issue by Jikataaaa** [luchob/softuni-sept-2021-misc#112]
Здравейте, при опит за логин със съществуващ юзър, ми се хвърля този ексепшън java.lang.IllegalArgumentException: Hex-encoded string must have an even number of characters. От няколко дни се боря с него и не мога да го оправя, моля за помощ. 
Линк към проекта https://github.com/Jikataaaa/SpringProject

**Comment by luchob** [comment]
Здравей!

Причината е, че си записал паролата на юзъра в plain text в DB, без да използваш passwordEncoder.

Трябва да направиш това:

```
        user.setPassword(encoder.encode("asd"));
```

Вместо:

```
        user.setPassword("asd");
```
 
Като `PasswordEncoder encoder` би могъл да инжектираш в конструктора.

Поздрави,
Л.

**Comment by Jikataaaa** [comment]
При регистрация на юзър и след това логин с тези данни, отново се хвърля същата грешка.

**Comment by luchob** [comment]
Да, така е. Защото паролата не трябва да се записва в plain text в DB, както правиш:

```
@Override
    public void registerUser(UserServiceModel userServiceModel) {
        User user = modelMapper.map(userServiceModel, User.class);
        repository.save(user);
    }
```

По-скоро трябва да е нещо от сорта:

```
@Override
    public void registerUser(UserServiceModel userServiceModel) {
        User user = modelMapper.map(userServiceModel, User.class);
        user.setPassword(encoder.encode(userServiceModel.getPassoword());
        repository.save(user);
    }
```
Като PasswordEncoder encoder би могъл да инжектираш в конструктора. Паролата трябва да мине през енкодъра и в ДБ да се пази хеша и, в противен случай няма да работи.

Поздрави,
Л.

**Comment by Jikataaaa** [comment]
Благодаря, за отговорите, справих се с проблема.
Лек и успешен Ви Желая.
