### ISSUE TITLE
Проблем с logout и с exceptionHandler 

### ISSUE THREAD

**Issue by Jikataaaa** [luchob/softuni-sept-2021-misc#113]
Привет, след логин, когато се опитам да logout-на, но хем spring security нещо не сработва и не се показва страницата за грешка (error page). линк към проекта : https://github.com/Jikataaaa/SpringProject

**Comment by luchob** [comment]
Добро утро!

Да, не сработва, защото логаут линка ти е GET заявка. А трябва да бъдеPOST (заради CSRF). Ето как изглежда при теб:

```
                <li><a th:href="@{/user/logout}">Logout</a></li>
```

Това го споменавахме на няколко пъти, но все пак ако има нужда от конкретен пример може да погледнеш в mobilele. Там е направено така:

```
            <form th:action="@{/users/logout}" th:method="post">
              <input class="btn btn-link nav-link" type="submit" value="Logout">
            </form>
```

А ето и точен [link](https://github.com/luchob/softuni-sept-2021-misc/blob/master/mobilelele/src/main/resources/templates/fragments/navbar.html#L43).

Поздрави,
Л.
