### ISSUE TITLE
Динамично взимане на борсова цена на крипто през api

### ISSUE THREAD

**Issue by DanielOgnyanov** [luchob/softuni-sept-2021-misc#114]
Здравей Лъчо,

Имам няколко въпроса относно това как мога да взимам динамично цената на крипто валути и да я показвам на фроненда.

1. Добра идея ли е да взимам цените на крипто през въшно api което връща json. Ако  e тази информация която е върната да я запиша във базата и след това от там ли да я взимам всеки път или има и друг начин?  

2. Тъй като цената се променя и всеки път като правя call за да ми върне json със обновената информация всеки път ли да обновявам инфото запипсано във базата или е лоша идея . 

3. Прилагам пастебин със примерен call към външно api -----   https://paste-bin.xyz/25128  -------

Като цяло идеята ми е след като ми е върнат json със инфо за цената да го запиша във базата правейки дто и взимайки само нужните ми полета от този json филе. И тъй като цената се променя искам да направя метод който да прави този call през определено време със скедулинг и крон.

Начина по който искам да го направя ок ли е, или няма логика по този начин да процедирам и има по добър?

Благодаря ти

Даниел

**Comment by luchob** [comment]
Привет! 

Съжалявам за бавния отговор, но в събота е ден за чист въздух :-)

Относно 1) Ако само я показваш в фронтенда бих избрал (ако схемата на аутентикация позволява това) да вземам данните през Javascript във фронтенда. Мотивацията ми е, че по този начин бих разтоварил сървъра като цялата работа ще се върши от клиентските браузъри. 
Относно 2) и като продължение на 1. Що се отнася до курсове на валути, нещата би трябвало да са доста динамични и малки колебания в курсовете да водят до натрупване на грешчици, които биха могли да станат по-големи грешки. Тъй като информацията наистина е критична (едва ли на някой му е все тази дали ще даде 100 или 110 например) може би е редно да пръвиш чести ъпдейти, дори в момент на транзакция всичко да си става real time с call по REST.

Това че правиш чест ъпдейт в базата данни не е никакъв проблем. Дори е възможно да направиш in-memory-cache (учихме за Cachable анотацията). Едно голямо и нормално приложение прави хиляди заявки към ДБ всяка минута, така че прекалената оптимизация е нещо, което не се прави в начален момент.

По-скоро първоначално го правиш възможно правилно, лесно и не толкова оптимално, после ако се наложи преработваш.

JSON -> база -> крон е съвсем работещо решение. Единствения недостатък е, че в момент в който нямаш посетители крона ще си върти ненужно.

Поздрави,
Л.

**Comment by DanielOgnyanov** [comment]
Благодаря ти много Лъчо.
