### ISSUE TITLE
Реализация

### ISSUE THREAD

**Issue by chaneto** [luchob/softuni-sept-2021-misc#115]
Здравей, Лъчо.
Извинявай, че малко извън курса, но ако имаш време имам няколко въпроса които са взаимосвързани.
Първото нещо което искам да попитам е, колко е трудно човек на тези години да започне работа(питам, защото сме набори)?
Второ, колко е трудно да започне човек работа на тези години и без добър английски, понеже немския ми е по силната страна.
Трето, като се има предвид всичко това и след като нали съм преминал и този модул успешно, като препоръка сега английски ли да уча или да запиша js advanced, а може би HTML & CSS, понеже няма да имам време за две неща наведнъж?
Благодаря.

**Comment by luchob** [comment]
Привет, наборе :-)

Честно казано, не съм сигурен колко е лесно. По себе си усещам, че вече ми е по-трудно да уча от преди, все още здържам на натоварване, но на 20+ ми беше къде къде по-лесно. Чел съм, че за нашата сфера в Германия върха на кариерата е средно на около 47 години, оттам нататък следва падението и завършваш с околосветско за пенсия ;-) . В работата съм видял реализиран колега бивш адвокат с 10+ години адвокатска практика, също и дипломиран лекар (и двете професии са ги тренирали да четат много). Няколко души без някакви съществени умения, творчески личности и т.н. но не особено добри ИТ специалести. Английският е абсолютно задължителен, не мога да си представя ИТ, което не говори на английски. Най-малкото всичката документация е на английски език. В 95% от случаите ще работиш с чужденци и трябва да се разбираш с тях. Може да не е перфектен и литературен (лазурни синеви, трепетни усещания, фин като коприна), но трябва да е работен (обектът е от тип Integer, на потребителя трябва да му се покаже съобщение). Това, че говориш немски е супер. В БГ има много немски фирми и колегите от Германия наистина се радват ако говориш езика им. В немска фирма е голям плюс. Дори в момента често ми се налага да се боря с тикети на немски, с документации и т.н. а моя съвсем не е добър и е една мъка и борба неравна... JS е ок, но в ерата на single page app-s, енгулър и реакт е доста важно да може да се похвалиш с някакъв такъв фреймуърк. Например може да наблегнеш на typescript и angular, за да видиш как се навръзва с REST с Spring и става пълно решение. Има толкова много за учене.

Поздрави и весели празници!
