### ISSUE TITLE
Проблем с качване на снимка

### ISSUE THREAD

**Issue by dimitar1997** [luchob/softuni-sept-2021-misc#116]
Здравей, сблъсках се със следният проблем. При метода при който трябва да запазя определена снимка в static/images(а това е когата user-ра иска да добави ново заведение и го задължава да качи снимка), като идеята ми е пътя да го запазя в базата под формата на стринг. Та приложението винаги ми гърми. Разгледах неща в интернет и се допитах до един приятел и двамата сме без резултат как се прави това. Накратко не разбрах как се  upload-ва снимка. Много ще съм благодарен, ако може дами помогнеш. Прегледах стари лекции, но единствентото, което намерих е как да запишеш снимка, но вече с хардкорднати данни
Ето тук е приложението - https://we.tl/t-pF1e2cs5hn

**Comment by luchob** [comment]
Не бих препоръчал да правиш това, но ако все пак искаш хвърли едно око тук - https://stackoverflow.com/questions/29382381/write-file-into-spring-boot-folder

Но по-скоро тази статия ми се струва по-надежден източник :-)
https://frontbackend.com/spring-boot/spring-boot-upload-file-to-filesystem

Поздрави,
Л.
