### ISSUE TITLE
Google Cloud Platform

### ISSUE THREAD

**Issue by amdimov** [luchob/softuni-sept-2021-misc#117]
Здравейте и за много години. Пожелавам Ви щастлива и успешна година :-)

Извинявам се, че ви занимавам след курса, но можете ли накратко да ме насочите към подходящ курс 
или материали, от които можем да научим повече за deployment-а на проектите ни в GCP или AWT.

Откъде е най-добре да започна - Docker, Kubernetes и накрая GCP?
Намирам разни туториали, но сякаш не мога да сглобя пъзела между трите технологии.

За капак не мога да разбера изобщо и това ценообразуване на cloud услугите.
Сметката ми за момента е около 2000$ на месец, за да си кача проекта :-))

Ще се радвам, ако може да дадете някакъв кратък съвет откъде да подхвана.

Благодаря,
Александър

**Comment by luchob** [comment]
Здравей!

Сметката ти трябва да е не повече от 15-на долара, но нямам детайлите :-) Ползвам GKE (google k8s engine) и между другото K8s скоро [няма да поддържа докер](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/), което може би няма да се отрази на девелопмънта с докер.

Като източник за k8s мога да ти дам една МНОГО яка книжка - [Kubernetes in Action](https://www.manning.com/books/kubernetes-in-action-second-edition). Според мен ако искаш да надникнеш по-дълбоко в технологията - това е мястото. За другите две неща ми е трудно да ти посоч източник, който да ми харесва толкоз много.

Поздрави,
Л.

**Comment by amdimov** [comment]
Благодаря много, Лъчо! Започвам с книжката :-)

Приятен ден.
