### ISSUE TITLE
Spring Security 

### ISSUE THREAD

**Issue by DanielOgnyanov** [luchob/softuni-sept-2021-misc#118]
Здравей Лъчо,

Имам въпрос относно спринг и следната конфигурация, https://pastebin.pl/view/d34f7245
удачно ли е както съм го направил тоест на всяка заявка да се иска аутентикация и добра идея ли е във базата
след като статуса на заявката е ок да сложа една булева isLogged примерно за да знам при следващи заявки дали да връщам информация.
Пиша си фронтенда на Реакт и от там съм си направил нормален феч към апи при статус ок  да записва юсера във локал стораге и да сетва токен и ид. това ок начин ли е или не.  Защото при логин заявка към апи при положителен статус  трябва да върна ид  и това ме притеснчва дали е ок така или просто да връщам isLogged труе и да давам достъп към хоме и другите страници. Ти как би го направил какъв би бил твоя избор.

Прилагам Пасте бин за да е по ясно.

--> Java
https://paste-bin.xyz/35728 Rest Controller

--> React
https://paste-bin.xyz/35729 login component
https://paste-bin.xyz/35730 authService
https://paste-bin.xyz/35732 authContext
https://paste-bin.xyz/35733 localStorage

Извинявам се за въпросите но се чудя дали работя правилно и дали логиката ми е във правилната насока.

Благодаря ти много.

Даниел

**Comment by luchob** [comment]
Здравей!

За съжаление забравих да отговоря на този въпрос :-) Последните paste-bin-s са експайрнъли и за съжаление нищо не виждам там, но първия е ОК.

Там аутентикацията се извършва и после записва session id в cookie, което би трябвало да се праща от браузъра и да бъде прозрачно за теб, т.е. няма нужда да правиш нищо. Това да записваш някакви неща в local storage не мисля, че е опция.

Ако пък искаш да използваш външна аутентикация (напр. facebook, google login, etc.) то тогава хвърли очо на spring oauth. На клиентската страна с реакт не зная какво да ползваш, но например за енгулър съм ползвал https://github.com/damienbod/angular-auth-oidc-client . Все пак да предупредя, че не е съвсем тривиално да навържеш всичко.

Поздрави,
Л.
