### ISSUE TITLE
Независимо Ентити

### ISSUE THREAD

**Issue by chaneto** [luchob/softuni-sept-2021-misc#18]
Здравей, Лъчо. Срещам затруднения с условието на проекта, тъй като английския не ми е силната страна. Би ли ми разтълкувал значението "незавивисмо ентити" и би ли дал пример за няколко. 
Примерно:
User
Product
Category
Cart
Address,
незавивисми ли са, след като продукта трябва да съдържа в него си категория и примерно количката потребите?
Благодаря предварително.

**Comment by luchob** [comment]
Хей, привет! 

Тъй като не съм съвсем наясно с изпитния процес, този въпрос може да го зададете на Чочо или на Г.Николов. 
За да не съм пък съвсем безполезен звъннах на Чочо и му казах да обясни отново условието на изпита довечера, когато ще решите и един брой :-)

Поздрави,
Л.
