### ISSUE TITLE
trying pull request -> error: 403 (unable to access)

### ISSUE THREAD

**Issue by Ivan-Tashev** [luchob/softuni-sept-2021-misc#2]
Hello,
I've tryed pull request (both HTTPS and SSH) with micro modification on the CSS file from today, but your Repo returns:
remote: Permission to luchob/softuni-sept-2021-misc.git denied
fatal: unable to access 'https://github.com/luchob/softuni-sept-2021-misc.git/': The requested URL returned error: 403

Attached couple of scr shot's with the git commands i'm using...
Pls, advise ?
Thx!
<img width="814" alt="https" src="https://user-images.githubusercontent.com/67376621/133340532-9c9c9302-8b15-4c7e-b671-d016b2a29565.png">
<img width="812" alt="ssh" src="https://user-images.githubusercontent.com/67376621/133340536-50182029-e13f-40df-931b-a233466e4950.png">
<img width="812" alt="branch" src="https://user-images.githubusercontent.com/67376621/133340538-3ba0df88-2b4a-4576-a64a-1fc5b8964bca.png">

**Comment by luchob** [comment]
Привет! 

Това е защото не си "collaborator". В подобни репозиторита се правят PR-и, когато направиш "Fork" на repoto в твоя акаунт, след това направиш промяната и тогава направиш PR от твоя форк в моето репозитори. Опитай да видим дали ще се получи.

<img width="149" alt="Screenshot 2021-09-15 at 9 48 47" src="https://user-images.githubusercontent.com/10339738/133384399-4f6d6227-2bf2-4b87-95d8-267c02607569.png">

Поздрави,
Л.

**Comment by luchob** [comment]
https://github.com/Ivan-Tashev/Ivan-Tashev/pull/1
