### ISSUE TITLE
one more mapper - MapStruct ?

### ISSUE THREAD

**Issue by Ivan-Tashev** [luchob/softuni-sept-2021-misc#29]
Здравейте,
може ли в някои от следващите Workshop-и (пример:Pathfinder), да направим мапваме м/у модели с MapStruct, като разнообразие, алтернатива на използвнаите "инструменти" (ModelMapper) ?

@Mapper
public interface MyMapper {
    MyMapper INSTANCE = Mappers.getMapper(MyMapper.class );
 
    @Mapping(source = "prop1", target = "prop2")
    SomethingModel SomethingToSomethingModel(Something something); 
}

Относително, картко е запознаването с него, и мисля ще бъде интересно на всички...
Поздрави,
И.

**Comment by luchob** [comment]
Добреее, лесно е да се ползва наистина, интересното тук е че става с анотейшън процесор. Което е доста различно като принцип на действие от модел мапъра. Ще гледам да го "боднем" в демото за HATEOAS, което и без това е доста скучно :-)

**Comment by luchob** [comment]
Done :-) Добра идея!
