### ISSUE TITLE
Здравейте

### ISSUE THREAD

**Issue by rancho83a** [luchob/softuni-sept-2021-misc#30]
How to change atCommonLocations()?

Ако все пак ми трябва ресурсите със снимките да са в папка с име "img", а не "images", какъв е синтаксиса на настройката:
                .requestMatchers(PathRequest.toStaticResources().atCommonLocations()).permitAll()
с какво да сменя ".atCommonLocations()"?
Благодаря.

Засега не успявам да намеря решение.

**Comment by luchob** [comment]
Здрасти!

Пробва ли със
`antMatchers("/img/**").permitAll()` :-)

Поздрави,
Л.

**Comment by rancho83a** [comment]
Пробвах, не стана.
 Най-вече защото .atCommonLocations() се отнася за PathRequest.toStaticResources(),  a опцията, която предлагате .antMatchers("/img/**").permitAll() - не може да се извика за PathRequest.toStaticResources().


 
 Опциите, които има PathRequest.toStaticResourc са:
 
![image](https://user-images.githubusercontent.com/73530200/140311585-471cf5c4-3423-4d80-8844-b445dca8c8a5.png)


само  .at(StaticResourceLocation...) , където StaticResourceLocation е  enum class:  StaticResourceLocation.java 
, който не мога да променя. (В него са дефенирани IMAGES("/images/**")

Има ли как да кажа, че за моя проект това  IMAGES("/images/**") ще бъде  IMAGES("/imг/**")...

Вече е въпрос на интерес, не е нещо необходимо, ще си прекръстя навсякъде img в images...

**Comment by luchob** [comment]
Ехх, явно аз не обясних добре. Сещам се един образ какво разправяше: "Ако седя в една стая и обяснявам нещо на 10 души и един не разбере - зная кой е глупака. Ако обяснявам нещо и 10-те не разберат - пак зная кой е глупака" :D 

Та така, ето я конфигурацията, примерна:

<img width="790" alt="Screenshot 2021-11-04 at 18 30 59" src="https://user-images.githubusercontent.com/10339738/140379988-9728b00a-9e66-49eb-95ae-d16f3c39d65f.png">

И резултата, когато отворя картинката:

<img width="1156" alt="Screenshot 2021-11-04 at 18 32 03" src="https://user-images.githubusercontent.com/10339738/140380143-5b4b3ccc-c479-4f77-afa8-4607a85218ef.png">

Без горната настройка, се получава 302 и редирект към логин страницата:

```
curl -v http://localhost:8080/img/code.png
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /img/code.png HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 302 
< Location: http://localhost:8080/users/login
```

Поздрави,
Л.

**Comment by rancho83a** [comment]
Всичко пределно ясно. То някой трябва да се сети, че по всичките html трябва да се върне от "image" на "img",  за да сработи... голяма излагация.
Благодаря ви.
