### ISSUE TITLE
Jpa връзки

### ISSUE THREAD

**Issue by svilen-rusev** [luchob/softuni-sept-2021-misc#32]
Здравейте, имам малък проблем с връзките между различните ентитита, станаха много връзки и се омотах кое с кое трябва да бъде свързано, особено с ManyToMany релацията. Може ли да го погледнете когато сте свободен, и да ми кажете кое ми липсва. 

Качил съм ги тук -https://ln5.sync.com/dl/7003a7dc0/9p944ig3-5f77ivhq-bfeiuhdb-7gccjv87
И обяснение -https://ln5.sync.com/dl/1ac0ad9f0/r8i6jc9v-2c5r7w9r-y9y3etyk-mnasc4j8

**Comment by luchob** [comment]
:-) Привет! Въпросът е доста общ, проектът е обемен и имам два варианта. Или да седна за ден два и да го направя :-) или да се опитам да ти давам акъл по-малко и да ми казваш дали си ок с идеите. Съветът ми е - първо се опитвай да си разпишеш таблиците, после с ентититата ще е малко по-безболезнено.

Да започнем с програмите за храни, например (FoodProgram).  Тук виждам 4 таблици, да кажа какво имам предвид:

Тъй като съм вегетарианец да направим една програма за мен.

Вегетарианска програма 
- закуска маруля + морков
- обяд репички
- след тренировки - морков
- вечеря - цвекло

Цел: да се избавим от мъките

Тук виждам четири таблици:
Food:
```
Id|name
----------
1 |Маруля
2 |Репички
3 |Морков
4 |Цвекло
5 |Пържола
```

Meal:
```
Id|type           |description
-----------------------------------------
1 |закуска        |сутрешен power
2 |обяд           |почерпка
3 |след тренировка|...
4 |вечеря         |....
5 |вечеря         |пържоли по пернишки
```
Meal_Food:
```
Id|Meal_id|Food_id|
---------------------
1 |1      |1      |
2 |1      |3      |
.....
```

Food program:
```
Id|breakfast_meal|lunch_meal|after_ex_meal|dinner_meal|goal            |totalCalories|
------------------------------------------------------------------------------------
1 |1             |2         |3            |4          |да се отървем...| 100         |
```

1. Звучи ли ти това ОК?
3. Ако - да - можеш ли да направиш ентититата така че да се отговарят точно на този модел?
3. Ако не - защо?
4. Интересен въпрос - къде ти се струва най-удачно да сложиш/преместиш калориите?

Така по-лесно ли е?

Поздрави,
Л!

**Comment by svilen-rusev** [comment]
Първо, благодаря за отговора.
Сега като се замисля, се оказа по-сложно отколкото си мислих в началото. Ако правилно съм разбрал, тук по Вашият план имаме, 3 Entity таблици и една таблица създадена автоматично след релацията? Относно калориите си мислих да бъдат в Food program, като калории прието от всичките хранения за деня, примерно 2000-3000 за деня.

**Comment by luchob** [comment]
:-) Замисляш се съвсем правилно, коравичко ще става:-) Това е само началото, обаче. Да имаме 3 ентитита и една relation таблица. За калориите за се двоумях между фууд и фууд програма, но това е по-скоро "бизнес" решение отколкото техническо, така че го оставям на теб.

**Comment by svilen-rusev** [comment]
Имам въпрос, който ме не мога да разреша от вчера, как да направя, така че с едно поле да направя 4 таблици за различни ядения, без да правя 4 полета(поради факта, че са едни и същи и fetchtyp.EAGER няма да работи). Има ли вариант с тази антоция както тук да добавя още 3 таблици или нещо подобно?
https://pastebin.com/YKMbpWNr

**Comment by svilen-rusev** [comment]
Моят проблем е решен, така че последния въпрос отпада.
