### ISSUE TITLE
OFF - Internationalization/i18n

### ISSUE THREAD

**Issue by amdimov** [luchob/softuni-sept-2021-misc#33]
Здравейте.

Когато е удобно, бихте ли ми дали насоки за добрите практики в създаването на мултиезично съдържание.
Четох в интернет и се пропоръчва да се направи с LocalResolver и разни .properties файлове.
Любопитно ми е дали може да се направи по-динамично т.е. в самта база, така че да има възможност (подобно на WordPress) да се създаде страница с няколко варианта на различен език. Това предполагам няма как да стане с properties файлове? Чудя се дали има има някаква библиотека за тази цел?

Поздрави

**Comment by luchob** [comment]
Здравей!

Дааа, с удоволствие. Защо мислиш, че няма да стане с пропъртийз файлове. Точно това е начина. Направих едно демо - разбираемо ли е? 

https://github.com/luchob/softuni-sept-2021-misc/tree/master/i18n

Поздрави,
Л.

**Comment by amdimov** [comment]
Благодаря много за разяснението и демото :-)
Последните дни си поиграх с примерния код и ми стана ясно как се прилага, но не съм сигурен, че напълно разбирам как се случва самата конфигурация в Spring. 
Предполагам, че e нещо подобно- LocaleResolver създава cookie, което да държи Locale, а LocaleChangeInterceptor следи за подаването на query параметър? Не мога да разбера как двете са свързани и дали Locale има връзка с хедърите в рекуестите. Малко е каша за сега, но се надявам да се избистри :-)

Поздрави,
Александър

**Comment by luchob** [comment]
То целия спринг е малко кашица, ама не го казвай на другите, моля :)

`LocaleResolver` е интерфейс, на който може да поискаш да резловне локала базирано на HTTP рикуест или да му сетнеш такъв в контекста на HTTP request:

```
public interface LocaleResolver {
	Locale resolveLocale(HttpServletRequest request);
	void setLocale(HttpServletRequest request, @Nullable HttpServletResponse response, @Nullable Locale locale);
}
```

`LocaleChangeInterceptor` e Spring interceptor (учихме ги :) ) който просто следи за някакъв куери параметър, взема текущия локал резолвър и го нотифицира какъв е новия език:

```
@Override
	public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler)
			throws ServletException {

		String newLocale = request.getParameter(getParamName());
		if (newLocale != null) {
			...
				LocaleResolver localeResolver = RequestContextUtils.getLocaleResolver(request);
				...
				localeResolver.setLocale(request, response, parseLocaleValue(newLocale));
			
		}
	   ...
	}
```

Самите локал резолвъри са най-различни, но специално този който работи с кукита добавя куки в респонса ако е нотифициран за смяна на езика. Ако пък извикаш `resolveLocale` се опитва да парсне съответното кууки.

Значи накратко:

1. `http://localhost:8080/somethig?lang=en_US`
2. LocaleChangeInterceptor - упс! Чакай да нотифицирам LocalResolver-a
3. LocaleResolver - някой ми смени езика! Чакай да го асоциирам с текущия рикуест.
4. LocalResolver - след като го асоциирах с текущия рикеуст ще направя и едно кууки за браузъра, да да дойде това кууки следващия път.

Spring (Thymeleaf и т.н) някъде след 3) 
LocaleResolver - да й ми текущия локал ако е асоцииран с рикуеста, ако ли не го извади от кууки което идва в рикуеста.

Е нещо ей такова, не знам дали стана по-ясно вече :-)

**Comment by amdimov** [comment]
Няма да казвам, макар че съм сигурен, че са наясно :-)

Сега разбирам как работи, но проблемът е, че не открих никъде в Stackoverflow или другаде така достъпно обяснение т.е. когато завършим скоро, ще има да се почесваме докато си разясним даден проблем :-)
но тогава ще му мислим..

Благодаря отново и приятен ден.

**Comment by luchob** [comment]
BTW, говорих с Георги от СофтУни. Това нещо ще се признае за употреба на интерсептор на изпита. :-)

**Comment by amdimov** [comment]
Здравейте.

Едно последно нещо относно i18n :-)

Възможно ли Locale да се променя не с query param, а с path variable?
т.е. от example.com/example?lang=de на example.com/de/example
От доста време се опитвам и не откривам решение. 
Пробвах няколко неща и сякаш най-близо е чрез
екстендване на LocaleChangeInterceptor-a, но все пак резултатът е по-скоро каша.

Дали изобщо е възможно да се направи със Spring Security?

Ако е твърде сложно или не е добра практика със Спринг, може да забравим този въпрос :-)

Поздрави,
Алекнсадър

**Comment by luchob** [comment]
Привет!

Не случайно резултатът е каша. Защо точно:

```
example.com/de/example
```
А не:

```
example.com/example/de
de.example.com/example
```

Но когато става въпрос за подобни гимнастики, нещата би трябвало да тръгнат в посока URL rewriting. Например, вместо:

```
http://example.com/products/1/details
```

Нещо като:

```
http://example.com/super-nice-gadget
```

Последните УРЛ-та са много важни, защото търсещите машини ги обичат. Чувал съм и съм ползвал някои решения:

1. В интершоп проекта в старата ми работа нещата ставаха с някаква къстъм боза с regexp, беше страшно :-)
2. В LAMP света е [mod_rewrite](https://httpd.apache.org/docs/2.4/mod/mod_rewrite.html)
3. В wordpress май се пазеха в ДБ, пак доста къстъм решение
4. В Java/Tomcat/Spring има някакъв проект [UrlRewriteFilter](http://tuckey.org/urlrewrite/). Не съм го ползвал, но май има известност :-) То се инсталира като сървлет филтър.

Та идеята е, ако толкоз много си решил да тръгнеш по този път с path variable, може би си струва да инвестираш малко време в някакаъв url-rewriting за да може example.com/de да се пренапише на example.com/?lang=de. Няма да е лесно, обаче ;-)

**Comment by amdimov** [comment]
Ясно, ще остане за по-нататък :-)

Да, опитвах се именно заради търсачките, но може би засега ​ще си направя проекта както предложихте -
de.example.com/examplе или просто на друг домейн.
Предполагам, че когато понауча React или Angular този проблем ще се реши.

Благодаря много за отговора и отделеното време.

**Comment by luchob** [comment]
> Предполагам, че когато понауча React или Angular този проблем ще се реши.

Тц, съмнявам се че ще се реши дори и тогава ;-)

Но когато се научиш как да настроиш уеб сървъра, който ти хоства енгулър приложението (apache, nginx, iis, etc.) със сигурност ще се реши :))

Поздрави,
Л.
