### ISSUE TITLE
Проблем с финалния проект

### ISSUE THREAD

**Issue by mitko3009** [luchob/softuni-sept-2021-misc#34]
[FinalProject.zip](https://github.com/luchob/softuni-sept-2021-misc/files/7487889/FinalProject.zip)
Здрасти Лъчо. Проблемът е следния: Имам горе долу скелета на проекта, който съм сглобил с помощта на темплейти от Bootstrap. когато ги теглех един по един използвах редактора sublime text за да мога просто да навържа страниците една за друга с бутоните и да видя приложението. След като реших че ще го пусна в InteliJ на всички останали страници  освен index.html и home.html не ми зарежда никакви статични ресурси (css,js....). Много ще съм благодарен ако погледнеш. Благодаря предварително.

**Comment by luchob** [comment]
Здравей! Импортнах проукта ти при мен в IntelliJ и го пуснах, няма никакъв проблем да тръгне и HomeController-a си редиректва към хоум страницата. Прилагам снимчица. Допускам, че проблема е по-скоро в твоя ТВ. Това, което ти предлагам е:

1. Изтрий iml файла
2. Изтрий target папката
3. Импортни пак проекта
4. Отвори dev tools и се увери, че заявките са правилни и/или виж коя от тях фейлва. Виж моя скрийншот, там отдолу се вида какво минава и какво - не.
Импортнал съм проекта без модификации.

<img width="1382" alt="Screenshot 2021-11-06 at 15 46 57" src="https://user-images.githubusercontent.com/10339738/140611937-ad3b12cd-e1c3-47e8-bde6-9e7983a89657.png">

Поздрави!

**Comment by luchob** [comment]
Упс, всички останали ОСВЕН :-) Сори, връщам се от баирите и съм малко уморен и ме пече слънце цяр ден, хаха. Сега ще видя какво не е наред. Извинявай и игнорирай предния коментар!

**Comment by luchob** [comment]
Привет отново! 

Проблемът е елементарен и не е виновна IntelliJ, защото рядко тя е виновна :-) Само че, искам не само да ти го посоча, а да ти покажа как сам веднага да откриваш такива неща. Отваряш дев туулс и показваш мрежовия панел:

<img width="1082" alt="Screenshot 2021-11-06 at 15 55 24" src="https://user-images.githubusercontent.com/10339738/140612315-eed5603c-5042-429d-bb13-b100990b2122.png">

И какво да видим ;-) Търси статичните ресурси на път: `http://localhost:8080/users/vendor...` вместо на `http://localhost:8080/vendor...`. Защо става така? Защото ползваш _релативен_ път. Когато напишеш така: `href="vendor/mdi-font/css/material-design-iconic-font.min.css"` му казваш: търси ми бла-бла-бла.css на път, относителен спрямо текущия път, който е `http://localhost:8080/users`. Когато обаче му кажеш: `href="/vendor/mdi-font/css/material-design-iconic-font.min.css"` (начална наклонена черта) означава, търси ги на път, който е релативен на пътя на сървъра, който е: `http://localhost:8080`. Това вече е съвсем друго и макар и пак да е грешно в контекста на томкат ;-) ще работи. Правилното е да ползваш thymeleaf, а именно:

```
<link th:href="@{/vendor/mdi-font/css/material-design-iconic-font.min.css}" rel="stylesheet" media="all">
```

И войля:

<img width="681" alt="Screenshot 2021-11-06 at 16 06 05" src="https://user-images.githubusercontent.com/10339738/140612520-9c4d9201-6b9c-4cfe-b787-afb95ae86aef.png">


Следващият път - dev tools -> поглед и съм уверен, че сам ще се справиш!

Поздрави,
Л.

**Comment by luchob** [comment]
За да не остане "магия" и нещо неясно само да поясня думите си:

"и пак да е грешно в контекста на томкат"

Проблемът тук е следният - може да имаме един томкат сървър с инсталирани 2 спринг приможения, напр. моето lucho-app и mitko-app. Тогава твоите ресурси ще са на `http://localhost:8080/mitko-app/css/...` а моите на `http://localhost:8080/lucho-app/css/...` Thymleaf може да се оправя с подобни инсталации, затова и препоръчвам ползването на `th:href` :-)

**Comment by mitko3009** [comment]
Много благодаря за изчерпателния отговор! Със сигурност другия път ще ползвам dev tools и ще се опитам сам да оправя проблема. Днес времето беше хубаво и се надявам да си покорил някой нов баир който да носи незабравими спомени. Препоръчвам ти района на Урдини езера ако не си ходил определено ще ти хареса : ). Поздрави и на теб приятна заслужена почивка.
