### ISSUE TITLE
final project - login page issue

### ISSUE THREAD

**Issue by kostadinov111** [luchob/softuni-sept-2021-misc#35]
Здравей Лъчо,
искам да те помоля за съвет къде да потърся проблемa, който имам при опит за логване в моя проект.
Основно съм се водил от лекциите за mobilelele. Имам работеща регистрация, но когато се опитам да се логна с потребител, който вече е регистриран получавам по-долу описаната грешка.

register controller-a: https://pastebin.com/FgP7WYZV
login controller-a: https://pastebin.com/6pdiAa7W
AppSecurityConfig-a: https://pastebin.com/7bJ0AP5m
login page: https://pastebin.com/nSVfi9dE

В момента, когато се зареди login page и въведа валидни user и password ме препраща към следния адрес:
http://localhost:8080/static/css/nav.css
А в тялото на браузъра ми изписва следната грешка:

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sun Nov 07 23:05:14 EET 2021
There was an unexpected error (type=Not Found, status=404).
No message available

Ще съм много благодарен за всякакви съвети или препоръки.

Поздрави,
Георги.

**Comment by luchob** [comment]
Привет, Жоро!

Проблемът ти е доста прост. Както виждаш, това URL е грешно - `http://localhost:8080/static/css/nav.css`. Допускам, това е правилно - `http://localhost:8080/css/nav.css`.  Също така допускам, че първото грешно УРЛ се намира някъде из страниците, на които се приземяваш след логина. Спринг се опитва да зареди CSS-a от първото URL и се получава един редирект към error пейджа, който виждаш.

Поправи си линковете към CSS-a в HTML страницата и всичко ще заработи.

Поздрави,
Л.
