### ISSUE TITLE
Проблем с финалния проект

### ISSUE THREAD

**Issue by valeriayankova** [luchob/softuni-sept-2021-misc#36]
Здравей, Лъчо! :) 
Мъчи ме следния проблем - в проекта имам 2 ентитита Recipe и Product, като в рецептата имаме колекция продукти.
Когато даден юзър добавя нова рецепта, той има опция да добавя n на брой продукти, като добавянето на нови редове за продуктите съм направила с jquery. Въпросът ми е свързан с това как бих могла да взема цялата рецепта с всички продукти като binding model? Пробвах с thymeleaf, но като цяло доста безуспешно и всякакви насоки са повече от добре дошли! :)

**Comment by luchob** [comment]
Привет! Нали знаеш, че обичам да повтарям какво съм разбрал :-)

Разбрал съм, че имаш форма с един парънт обект (рецепта) и няколко продукта към нея. Трябва да събмитнеш формата и да създадеш всичко накуп. Тук има няколко подхода. Според мен за най-близкия до това, което искаш можеш да намериш жокер във въпроса на колегата - https://github.com/luchob/softuni-sept-2021-misc/issues/15

Това е с чиста HTML форма, където можеш да имаш нещо като индекси на обектите. 

Най-далечният е с REST API, където обръщаш формата в JSON и я подаваш на REST контролер.

Доколкото разбирам въпроса, питаш за първото нещо.

Поздрави,
Л.

**Comment by valeriayankova** [comment]
Здравей отново :) 
Страшно много благодаря за жокера, проблемът е решен! :)
