### ISSUE TITLE
Вероятен бъг в регистрацията.

### ISSUE THREAD

**Issue by FreshyMc** [luchob/softuni-sept-2021-misc#37]
Прегледах как работи последната версия на регистрацията за Мобилелеле-то и не разбирам къде правим проверка дали даден потребител с дадено име не е било регистрирано предварително. Мисля, че е пропуснато освен ако Spring Security не се грижи за това.

**Comment by luchob** [comment]
Здрасти! :)

Мисля, че все пак сме предвидили това, на ред [26 в байдинг модела](https://github.com/luchob/softuni-sept-2021-misc/blob/master/mobilelele/src/main/java/bg/softuni/mobilelele/model/binding/UserRegistrationBindingModel.java#L26). Все пак нещо е пропуснато (почти умишлено) и ми се иска днес да поговорим за него. В прочутите топ 10 [класации на OWASP](https://owasp.org/www-project-top-ten/) се нарича [broken access control ](https://owasp.org/Top10/A01_2021-Broken_Access_Control/) и заема първо място като уязвимост в последните класации. Можеш ли да го забележиш? :) Днес ще предложа 3 решения, от които да изберете за проектите си, тъй като очевидно от класацията това е доста важно в практиката.

Поздрави,
Л.

**Comment by FreshyMc** [comment]
Здравей! :)
Май го забелязах, не се знае какво ще стане ако полето е nullable. Защото връщаме true при проверката за null във имплементацията на валидатор имлементацията. Това ли е?
Лек и успешен ден!

**Comment by luchob** [comment]
Не, не е :-) Довечера ще поговорим за него. Всъщност, ако полето е null ще фейлне валидацията. Защото:

```
  @NotBlank
  @Size(min=4, max=20)
  @UniqueUserName
  private String username;
```

Поздрави и до после!
