### ISSUE TITLE
logs с AspectJ и @PointCut на метод, задължава връщаното View видимо САМО за Logged-In потреб

### ISSUE THREAD

**Issue by Ivan-Tashev** [luchob/softuni-sept-2021-misc#39]
Здравейте,
днес, зададох следния въпрос:

_<adv> пиша Integration Tests, открих че статистиката която съм направил с AspectJ и @PointCut на определен метод, ме задължава връщаното View да е видимо САМО за Logged-In потреб., защото log entity-тo има User, но НЕ бих искал това поведение? трябва да е видимо за вс., някакви насоки?_

ВСЪЩНОСТ НАМЕРИХ РЕШЕНИЕ! но все пак, помолихте да изпратя проекта, прилагам линк с конкретния commit на work around-a на горе описания проблем.

https://github.com/Ivan-Tashev/Obag/commit/b79512890528462c63628f3fd6c7aa07d68bb1ca

Ако, не сте съгласен, или не Ви допада... пишете.
Поздрави,
И.

**Comment by luchob** [comment]
Хей, привет!

Абсурд да го бях разбрал въпроса без да видя код. Нулев шанс :-) Да не говорим, че и след като го видях малко време ми трябваше...

Първоначално се смръщих леко защото ми стана интересно, защо искаш лог само за аутентицирани юзъри? Т.е. в тази статистика не е ли важно какво става и при анонимните юзъри? Някакви такива размисли, разбира се на ниво "post-exam". Изпитът е ясен :-) Можеш да проверяваш за анонимна аутентикация винаги. Това го пише в документацията, сякаш специално за твоя случай :-) :

_There are other situations where anonymous authentication is useful, such as when an auditing interceptor queries the SecurityContextHolder to identify which principal was responsible for a given operation. Classes can be authored more robustly if they know the SecurityContextHolder always contains an Authentication object, and never null._

[Link](https://docs.spring.io/spring-security/site/docs/4.0.x/reference/html/anonymous.html).

**Comment by Ivan-Tashev** [comment]
Привет и Благодаря за размишленията!

Принципно в сега действащият ни App липсва точно тази бизнес логика, проследяваща поведението - "разлеждани продукти и тяхната последователност" (имаме разнородни справки продажби/поръчки/показвания, но не и поредсноста преди да се стигне до поръчка) на логнати/идентифицируеми потребители...

Мениджмънт идеата е да се проследи, кои продукти от кои категории се разглеждат и в каква последoвателност, заедно с Втората статистика за най-разглеждани прдукти (която лесно мога да отворя, като броя view-тата на вс user), и евентуално незавършени колички (TODO) биха дали доста пълна картина за поведението до момента на Поръчка...

Отн. Анонимните user-и, първоначално мислех да създавам нови Random username entity-та, които да записвам в този лог, и на месечна база @Sheduler-a да ги затрива, но така ще си  "замърся" (напълня)  с много ненужни user-и таблицата... Върти ми се друга идея, да закачам по едно Cookie към Анонимните GET request-и, за да идентифицирам последващи Анонимни заявки, като предварително си създам един определен служебен User, които да записвам/проследявам в този Log, нo може би доста и излищно усложнявам логиката...

Освен това, бизнес погледнато, ще има известен "брак" от различни Анонимни юзъри, които просто ще влязат чекнат най-популярните продукти и gone... което изкривява малко идеята, за "поведение преди действителна поръчка", или "поне user които има регистрация и вероятно предходни поръчки".

Поздрави, И.
