### ISSUE TITLE
Малко помощ с една функция

### ISSUE THREAD

**Issue by HristoManov91** [luchob/softuni-sept-2021-misc#40]
Здравей Лъчо.Имам един проблем от известно време,на който не мога да намеря решение.В моят проект има функция да се добави продажба(Sellers -> Add sale) и там трябва потребителя да си добави продажбата която е направил,но проблема е че не мога да намеря начин как да има динамичен брои полета за Select Product,защото в една продажба може да има 1 , 5 , 15 , 40 продадени продукта.Самата ми идея е може би да има някакъв малък бутон до полета с текст Add който просто да изпраща избраният продукт в някакъв списък и над самото поле да почне да се трупа какво е добавено просто като текст за информация на User и когато е добавил всички продукти да натиска Submit.Оставям линк за проекта,за да може да го свалиш и стартираш и видиш въпросната функция както и някакво изображение на това,което си представям.Като приемам всякакви предложение дори и да не е по моя начин поне да работи пък във версия 2.0 ще го оправя.
https://github.com/HristoManov91/Celio
![Екранна снимка 2021-11-10 235022](https://user-images.githubusercontent.com/73854367/141199395-beefd454-b39b-43c4-aa29-7dd10e161d09.png)
П.С. Не обръщай внимание на красотата на сайта ще я оправя в по късен етап нея :D

**Comment by luchob** [comment]
Здрасти (без банда този път :D )!

Ти си третия поред човек с подобен проблем :-) Така че директно ти давам линка към другите двама, които успяха да се справят с малко подбутване - https://github.com/luchob/softuni-sept-2021-misc/issues/36

Поздрави,
Л.
