### ISSUE TITLE
OAuth2 регистрация

### ISSUE THREAD

**Issue by Bozhidarov8609** [luchob/softuni-sept-2021-misc#41]
https://github.com/Bozhidarov8609/Mucuna2021Final-master
Здравей можели малко помощ с регистрация чрез OAuth2. Направих нещата, които гледах в различни статии, но нещо не се получава. Предполагам, че е нещо малко. Това, което установих е, че програмата не минава през класа ми Auth2LoginSuccessHandler , а съм сложил обект от него в ApplicationSecurityConfig. При стартиране на приложението в страницата login съм сложил един <a th:href="@{/oauth2/authorization/facebook}">Login with Facebook</a>, в който като вляза ми дава да се логна с ФБ акаунта си, след това влизам в Home страницата, но не ми е регистрирал User. Благодаря предварително за помощта.

**Comment by luchob** [comment]
Упс! Привет! Може ли молко помощ? Откъде си направил линк за логин с фейсбуук?

<img width="1182" alt="Screenshot 2021-11-11 at 18 36 14" src="https://user-images.githubusercontent.com/10339738/141335219-a4b060fd-e0bc-4eb5-a025-c45f83b3e3fd.png">

**Comment by Bozhidarov8609** [comment]
Хахахаха. Трудно ще го намериш, когато не съм пушнал последния код който написах. Сега го има https://github.com/Bozhidarov8609/Mucuna2021Final-master. Не знам дали ще ти трябват но ти пускам и 
Values of EMAIL_PASS:  Globul11 
Values CLOUDINARY_SECRET:  mlO8Btv5kOF-IwTQD0iub-QxcL0.

**Comment by luchob** [comment]
Привет!

Извинявам се за бавния отговор, но вчера трябваше да се разходя в планините :P Така, виждам какво си направил и въпреки че OAuth логина ми е поизбледнял в паметта, моментално ти казвам, че success handler-a ти няма да се извика никога. Това е заради този код:

```
                .successHandler(oAuth2LoginSuccessHandler).
                defaultSuccessUrl("/home").
```

Ако видиш къде води кода на `defaultSuccessUrl`, то ще стигнеш до подобно нещо:

```
public final T defaultSuccessUrl(String defaultSuccessUrl, boolean alwaysUse) {
		SavedRequestAwareAuthenticationSuccessHandler handler = new SavedRequestAwareAuthenticationSuccessHandler();
		handler.setDefaultTargetUrl(defaultSuccessUrl);
		handler.setAlwaysUseDefaultTargetUrl(alwaysUse);
		this.defaultSuccessHandler = handler;
		return successHandler(handler);
	}
```

С две думи това нещо override-ва твоя success handler, който си сетнал на предния ред :-)

Едно време си бях писал такъв хендлър, който екстендваше `SavedRequestAwareAuthenticationSuccessHandler`. Кодът е [тук](https://github.com/luchob/tabula/blob/3612cc80572c973e652b25250119ea8e39f625ee/src/main/java/bg/softuni/tabula/user/OAuth2UserAuthSuccessHandler.java#L22).
