### ISSUE TITLE
Interceptors

### ISSUE THREAD

**Issue by chaneto** [luchob/softuni-sept-2021-misc#42]
Здравей, Лъчо.
Ако може малко просветление за Interceptors, че нещо...нищо не разбирам.
За проекта пише, че АОР е като бонус а в същото време  в задължителните изисквания пише (Use at least 2 Interceptors.), може ли да поясниш, че явно за пръв път ми е пълна мъгла.
Ако може също да ми дадеш насоки, примерно за онлай магазин къде и как може да се използва.
Нещо с Before and After или и аз не знам стрелям на посоки.
И още нещо, 
Ако имплементирам една търсачка дали ще покрие тези изисквания - (Use Fetch to asynchronously load and display data somewhere in your application.)?

**Comment by luchob** [comment]
Привет!

AOP и интерсепторите са съвсем различно нещо, като първото още не сме го учили. Така че, предполагам въпросът ти е за интерсепторите. Ще ти дам един пример със служебен за спринг интерсептор - локализация на сайта :-) Разгледай внимателно този въпрос от колегата - https://github.com/luchob/softuni-sept-2021-misc/issues/33
Дори тази локализация според хората от СофтУни би трябвало да се признае за употреба на интерсептор.

Разбери как работи и дори може да направиш и нещо подобно в твоя проект - защо не някаква тема за HTML-a?

За търсачката - ако използва fetch за да издърпа нещо по рест и да го визуализираш ще покрие, разбира се. Още по яко ще е ако измислиш как да правиш някакви suggestions докато пише, защо не?

Поздрави,
Л.
