### ISSUE TITLE
Проблем с логването

### ISSUE THREAD

**Issue by mitko3009** [luchob/softuni-sept-2021-misc#43]
Здрасти Лъчо. Дилемата този път е следната. При опит да логна потребител не успява да го логне и връща директно /users/login-error.Това е конфигурацията която ползвам прегледах пътища и имена дали всичко е наред и не открих проблем. При регистрация обаче успява да логне потребителя но не работи
logout бутона връща грешка 404. Когато опитам през логин формата да се логна в конзолата излиза че прави заявка към базата тоест сработва но явно не намира това което търси но дотам. Не знам в енкодера ли е проблема или къде но ме поизмъчи..Ще съм благодарен ако метнеш едно око. Благодаря предварително.
[Project.zip](https://github.com/luchob/softuni-sept-2021-misc/files/7520160/Project.zip)
.

**Comment by luchob** [comment]
Ей, Митко! Как е положението? :-)

Хвърлих две очи дори и всяко ти откри по 1 бъг, хаха :-)

Опитът ти да логнеш потребител засега е обречен на неуспех най-вече защото в логин формата ти параметъра, който държи паролата се нарича `pass` а в конфигурацията си му казал да се казва `password` -> `passwordParameter(UsernamePasswordAuthenticationFilter.SPRING_SECURITY_FORM_PASSWORD_KEY)`.

Т.е. все едно паролата ти никога не пристига на сървъра.

Логаут бутона също е обречен на неработене, защото този ендпойнт който е създал за теб спринг секюрити трябва да бъде "ударен" с POST заявка. Разгледай mobilele, там Logout наистина не е линк а е бутон, който събмитва форма!

Поздрави,
Л.

**Comment by mitko3009** [comment]
Благодаря Лъчо личи си че който си го може го може и проблемът е в задклавиатурното устройство. Гледах в mobilele но явно едното ми око още спи и недовижда леко. Жив и здрав бъди лека и спокойна вечер.
