### ISSUE TITLE
sec:authorize не работи за logout 

### ISSUE THREAD

**Issue by amdimov** [luchob/softuni-sept-2021-misc#44]
Здравейте,

Имам проблем, който не е болка за умиране, но ми се иска да открия причината. 
Ако имате време, бихте ли погледнали върпоса ми в Stackoverflow - [stackoverflow](https://stackoverflow.com/questions/69874210/spring-security-thymeleaf-templateinputexception-after-a-second-login)

Накратко,  login темплейта гърми, когато правя проверка дали юзърът е логнат за да не се показва logout бутона в навбара,.
`<li sec:authorize="isAuthenticated()" class="text-center logout"><form th:action="@{/logout}" th:method="post"><button title="LOGOUT" class="btn" type="submit"><i class="icon-off"></i></button></form></li>`

Замазах положението с `th:hidden="${logged}"` и ModelAttribute чрез @ControllerAdvice, но все пак ми се иска да открия причината, понеже ме гложди защо sec:authorize=isAuthenticated() не работи единствено за logout формата.

[Navbar Fragment](https://github.com/amdimov/print-shop-web/blob/main/src/main/resources/templates/fragments/essential/top_bar.html)
[Login Template](https://github.com/amdimov/print-shop-web/blob/main/src/main/resources/templates/login.html)
[LoginController](https://github.com/amdimov/print-shop-web/blob/main/src/main/java/com/example/transferhall/web/controllers/LoginController.java)
[HttpSecurity](https://github.com/amdimov/print-shop-web/blob/main/src/main/java/com/example/transferhall/config/AppSecurityConfig.java)

Поздрави,
Александър

**Comment by luchob** [comment]
:)

 Хех, мисля че знам какво се е случило и ти отговорих в SO. 
Сега ще видиш тъмната страна на Спринг и как един такъв проблем може да изяде дни от живота ти :-)

Поздрави,
Л.

**Comment by amdimov** [comment]
Ахх :) Наистина ми изяде няколко дни, а готово решение никъде. 
Благодаря много! :)

`csrfTokenRepository(new HttpSessionCsrfTokenRepository())` оправи проблема.
Правилно ли разбирам, че тази настройка в HttpSecurity прехвърля създаването на сесия от Спринг
преди Таймлийф?

П.С. Документацията ли помага за такова детайлно разбиране на какво се случва "под капака"
и такива решения да ни хрумват сами или по-скоро е опит?

Поздрави,
Александър

**Comment by luchob** [comment]
:-) По-скоро машинката работи приблизително така:

Интерфейсът `CsrfTokenRepository` позволява да се взема/запазва CSRF токън и Thymeleaf го използва. Само че дифоултната имплементация е т.нар. `LazyCsrfTokenRepository` която задържа генерацията на тоукъна до последно. Другия вариант е `HttpSessionCsrfTokenRepository`което генерира тоукъна на по-ранен етап, още преди да е отпътувал рикуеста към клиента. 

За разбиране какво става "под капака"... трябва да се отваря капака, да се пипа вътре, да се настъпват мотики, да се рови във форуми... Да, и от време на време не е зле да се чете малко документация, но това само по себе си е недостатъчно.

Поздрави,
Л.
