### ISSUE TITLE
Проблем при качване на файл.

### ISSUE THREAD

**Issue by FreshyMc** [luchob/softuni-sept-2021-misc#46]
Привет Лъчо!
Имам проблем при валидация на едно поленце в Binding Model.
Та полето е Set<MultipartFile> и е анотирано с @NotNull, обаче като не кача нито една снимка и при дебъг се популира с null валидацията минава сякаш има някаква стойност.
Чудя се да не би да има друга анотация за валидация на такъв тип полета?
Поздрави!

**Comment by luchob** [comment]
Привет!

В документацията на `NotNull` пише: "The annotated element must not be null. Accepts any type."  Т.е. ми е интересно, ако би могъл да ми дадеш пример, защото това което казваш ме учудва.

Не само това, но ако използваш multiple upload дори бих очаквал да имаш поне един multipart file в сета, тъй като полето с файла очаквам да се събмитне празно. Например заявката без файл би могла да изглежда така (chrome):

```
------WebKitFormBoundaryObI1BsJBQllD8QkP
Content-Disposition: form-data; name="myhtmlfield"; filename=""
Content-Type: application/octet-stream
```

Докато с 2 файла така:

```
-----------------------------118267066440769856382647329549
Content-Disposition: form-data; name="myhtmlfield"; filename="img1.jpg"
Content-Type: image/png

-----------------------------118267066440769856382647329549
Content-Disposition: form-data; name="myhtmlfield"; filename="img2.jpg"
Content-Type: image/png
````
Не съм сигурен, че ще можеш да се справиш със стандартните валидатори с това, и може би ще ти е необходим къстъм валидатор, така че байндинг модела да е нещо като:

```
@NotNull
List<@MyValidator MultipartFile> files;
```

Все пак искам да видя пример :-)

**Comment by FreshyMc** [comment]
Здравей отново!
Ето тук https://github.com/FreshyMc/InstamarketProject/tree/master/src/main/java/com/example/instamarket/model/binding
Проблема е в AddOfferBindingModel въпросното поле е с име offerImages
Има и две полета, които са от тип List и нямат анотации, но това е умишлено за целите на проекта.
А и също така още един въпрос. Имлементирах качването на файлове върху диска без cloudinary и направих отделен controller, който да прихваща заявките за снимките и да ги връща на потребителя. Страницата със снимките зарежда без проблем, но когато инспектирам снимката в браузара(отворя нов таб и напиша въпросният адрес на контролера) отговора е някакво китайско писмо. Опитах се да го направя както ти ми препоръча със ResponseEntity. Но проблема си е налице.
Поздрави от мен,
лек и успешен ден!

**Comment by luchob** [comment]
Упр! Относно втория въпрос го приех лично, тъй като препоръката беше моя :-)

Ами постави се на мястото на браузъра - изсипват му нещо и той не знае какво е. Следователно - китайско писмо. Трябва да му се каже, че всъщност това което пристига е картинка. Пример, с .png:
```
@GetMapping("/headingImage/{name}")
    public ResponseEntity showHeadingImage(@PathVariable String name) throws IOException {
        File f = new File(headingImagesPath + name);

        if(!f.exists()){
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }

        InputStreamResource inputStreamResource = new InputStreamResource(new FileInputStream(f));

        return ResponseEntity.ok()
            .contentLength(f.length())
            .contentType(MediaType.IMAGE_PNG)
            .body(inputStreamResource);
    }

```

Рзаковничето тук е `contentType(MediaType.IMAGE_PNG)`, което трябва да означава, че браузъра трябва да рендерира response-a като картинка, пристигаща в PNG формат.

За другото ще погледна ей сега.

**Comment by luchob** [comment]
Привет пак - сигурен ли си за това, което казваш? При дебъг в имиджите винаги има 1 файл и то никога не е null. Ето скрийншот:

<img width="907" alt="Screenshot 2021-11-14 at 17 40 15" src="https://user-images.githubusercontent.com/10339738/141687936-e6e344da-6411-419e-94e0-8bc0281eee5d.png">

Този файл е празен, поради причината, която казах по-горе. На първо слушане според мен ще е необходим къстъм валидатор. Ако говорим за валидатор на ниво целия байндинг модел - нещо от сорта на (c&p) от гугъл:

```
@Component
public class CustomFileValidator implements Validator{
public static final String PNG_MIME_TYPE="image/png";
public static final long TEN_MB_IN_BYTES = 10485760;
    @Override
    public boolean supports(Class<?> clazz) {
        return FileUploadModel.class.isAssignableFrom(clazz);
    }
 
    @Override
    public void validate(Object target, Errors errors) {
        FileUploadModel fileUploadModel = (FileUploadModel)target;
        MultipartFile file = fileUploadModel.getFile();
        if(file.isEmpty()){
            errors.rejectValue("file", "upload.file.required");
        }
        else if(!PNG_MIME_TYPE.equalsIgnoreCase(file.getContentType())){
            errors.rejectValue("file", "upload.invalid.file.type");
        }
       
        else if(file.getSize() > TEN_MB_IN_BYTES){
            errors.rejectValue("file", "upload.exceeded.file.size");
        }
       
    }
 
}
```

Т.е. според мен валидацията ти минава, заради този празен "файл" и ми се струва че трябва да напишеш къстъм валидатор.

Аз затова казах, че с клаудинари е по-лесно :-)) Ако не можеш да се справиш, пиши, натам ще помагам.

Поздрави,
Л.

**Comment by FreshyMc** [comment]
Лъчо ти си топ!
Значи оправих проблема относно показването на снимките в браузъра и се ориентирах благодарение на твоите препоръки, за които съм много благодарен!
Обаче за това с качването на файла не знаех, че ще е такъв таралеж в гащите. Все пак благодаря за насоките ще премисля как точно ще го напиша и ще пускам ъпдейти, за да помогнем и на друг колега ако се е решил да пробва да качва файл на сървъра без cloud.
Поздрави!

**Comment by luchob** [comment]
🎉
