### ISSUE TITLE
Проблем със скрипта

### ISSUE THREAD

**Issue by Polina-MD80** [luchob/softuni-sept-2021-misc#47]
Здравей, Лъчо
Голяма стъкмистика с фронтенда ми се заформя, и имам проблем как да направя и двете дропдаун менюта да работят в тая форма. Имам 2 скрипта, но само втория се задейства дори и като кликна на първото дропдаун меню. Може ли да погледнеш? https://pastebin.com/wK3Jw6V8

**Comment by FreshyMc** [comment]
Проблема ти е че ползваш var за декларация на променливите. Var има така нареченият global scope тоест ти със вторият скрипт презаписваш това, което е взето от горният. Моят съвет е да ползваш let за декларация на променливите и пробвай различни имена ако и двете променливи са с едно и също име в един и същ variable scope :-)

**Comment by Polina-MD80** [comment]
Много благодаря :). Така се случиха нещата.
