### ISSUE TITLE
Apache Kafka ()

### ISSUE THREAD

**Issue by Ivan-Tashev** [luchob/softuni-sept-2021-misc#48]

**Comment by Ivan-Tashev** [comment]
Здравейте,
какво мислите за малко демо или разговор на тема Apаche Kafka?

Интересна и различна концепция за съхранение на Event-и в topics (преди му казвахме log), и като цяло тренда към micro-services, които комуникират помежду си с messages на база event-и...

Поздрави, И.

**Comment by luchob** [comment]
Мисля, че идеята е супер. Първо, защото е интересно, второ защото има какво да споделя. 

В нашата фирма разчитаме предимно на кафка и много по-рядко на рест (когато ни е необходим синхронен отговор). Ако ти е интересно какво сме сътворили, [тук](https://www.youtube.com/watch?v=gHVxjWjagkk) има около 30 минутна презентация от мен. 

В лекцията Workshop And Q&A, частта с Q&A ще идва от вас. Като доколкото знам, ще ви пратят една анкетка в която можеш да напишеш предложението. 

Поздрави,
Л.
