### ISSUE TITLE
Проблем с инжектирането на UserDetailsService

### ISSUE THREAD

**Issue by vladikata2535** [luchob/softuni-sept-2021-misc#49]
Здрасти Лъчо,

[problem.zip](https://github.com/luchob/softuni-sept-2021-misc/files/7533629/problem.zip)
Имам проблем. Не иска да ми инжектира UserDetailsService. Хвърля ми тази грешка - Could not autowire. There is more than one bean of 'UserDetailsService' type.
Beans: deviceShopUserServiceImpl   (DeviceShopUserServiceImpl.java) inMemoryUserDetailsManager   (UserDetailsServiceAutoConfiguration.class) 

Как да го оправя да ми се инжектира без проблемно без да ми иска Qualifier ?

Поздрави,
Влади

**Comment by luchob** [comment]
Привет, Влади!

Сами по себе си тези класове не са ми достатъчни, за да ти кажа какво се случва. Защото ако направя празен проект с тях двата, той тръгва. 

Това което подозирам, е че имаш някаква друга настройка или нещо друго си експериментирал в проекта си (най-вероятно с настройка на im-memory аутентикация, оттам - inMemoryUserDetailsManager), която по подразбиране декларира друг bean. Който пък влиза в конфликт с твоя DeviceShopUserServiceImpl.

За да мога да ти кажа, трябва да видя целия ти проект и да мога да го стартирам. 

Ще чакам отговор.

Поздрави,
Л.

**Comment by vladikata2535** [comment]
Привет отново Лъчо,

Прикачвам ти проекта, за да можеш да го погледнеш и да видиш какъв е проблема.
[problem.zip](https://github.com/luchob/softuni-sept-2021-misc/files/7534886/problem.zip)

Поздрави,
Влади

**Comment by luchob** [comment]
Здрасти, Влади!

Много ми е трудно да ти отговоря на въпроса, защото в проекта ти не намирам нищо подозрително и когато го взех при мен, разпакетирах и го стартирах тръгна без драми. Прилагам скрийншот. Единственото, което промених беше паролата за ДБ.

Допускам, че има някакъв остатък при теб, който го кара да се държи така. Предлагам ти да изтриеш таргет папката, дори и файла на IntelliJ, да реимпортнеш проекта и да го компилираш наново. 

<img width="1433" alt="Screenshot 2021-11-15 at 8 20 18" src="https://user-images.githubusercontent.com/10339738/141733088-1ac689aa-16a2-4bfb-9962-d588c0cb9c6a.png">

Поздрави,
Л.
