### ISSUE TITLE
how Spring works under the @Annotations ?

### ISSUE THREAD

**Issue by Ivan-Tashev** [luchob/softuni-sept-2021-misc#5]
Здравейте,
извинявам се предварително за малко страничен/задълбочен въпрос, но:

### Как всъщност работи Spring fr под анотациите ?

Това което разбирам е, че се извършва сканиране @ComponentScan в пекидж и/или такива декларани в @Configuration бинове, които сканират за класове анотирани с @Component (или подвидовете му @Repo, @Service...) и чрез IoC(Inversion of Control) "поемат" контарола в/у тяхното инстанциране (т.е. избягваме традиционното new Xxxxx()) т.е. Spring го прави за нас, после чрез DI(Dependancy Injection) "вкарваме" и използваме в други класове/обекти... всичко това предполгам е рализирано чрез Reflection, които "чете" в runtime - класове/полета/методи, и подава на proxy обекти, но как точно... не ми е ясно кое от къде идва ?

Бихте ли ме насочили, къде мога да прочета повече информация ? или ако предцените да споделите кратко пред аудиторията ?
Поздрави,

**Comment by luchob** [comment]
Здрасти!

Може би ще е удачно да споенем няколко думи и пред останалите утре!

Поздрави!

**Comment by Ivan-Tashev** [comment]
от много време ме "мъчи" темата за тези proxy обекти, и все не остава време за тях, но мисля че я разгадах, накратко: 
Spring с помоща на @Анотации (пример: в нашите Services) създава Proxy обекти в/у които да се изпълняват различни функции. Като създаването на Proxy Instance изискава (ClassLoader, Интефейси(масив), и най-важното имплементация на InvocationHandler в/у самото прокси).
Самата имплементация на InvocationHandler-a зависи от нужната функция/задача дефинирана с Анотация.

Това много ми напомня, на времето когато в Нов обект/клас(пример SomeIfcNew) (сега рroxy) инжектирахме даден Интерфейс, и допълвахме/специфицирахме неговата фунционалност, и след това викахме този нов клас с new SomeIfcNew и подавхме имплементацията (от примера: new SomeImpl)...

На прав път ли съм, или греша ?


public interface Something { void something() }

public class SomethingImpl implements Something {
    @Override
    public String something() { return "Hi. " }

public class ProxySomething implements Something{
    private final Something something; // Ctor injected
    @Override
    public String something() { return something.something() + "Proxy!" }

public class Main {
    public static void main(String[] args) {
        Something somethingProxy = new ProxySomething(new SomethingImpl());
        somethingProxy.something();
    }

**Comment by luchob** [comment]
Здрасти! 

Малко ми е тъпо, че така препускаме по материала и се фокусираме върху някакви странни въпроси :-) вместо да говорим интересни нещица, но... За прокси обектите не съм се отказал да ги дискутираме в лекция, затова не затварям тикета. Но ето обяснение само с код. Ти беше пробвал спринг кеш, нали?

Ето ти е един `StudentService` дето има супер бавен и корав метод за извличане на студенти. [Тук](https://github.com/luchob/softuni-spring-advanced-2021/blob/master/proxies/src/main/java/bg/softuni/proxies/cache/StudentService.java#L7). 

Има анотация `@Cacheable` която инструктира да се кешира резултата. Това работи в спринг и е имплементирано в моя пример БЕЗ спринг и с чиста Java с прокси обект, възможно най-просто. Разгледай кода и имплементацията, елементарно е. 

Тук - https://github.com/luchob/softuni-spring-advanced-2021/tree/master/proxies/src/main/java/bg/softuni/proxies/cache

Тъй. Спринг използва или Java proxy-та (напр. Spring AOP) когато е възможно, или една библиотека CGLIB за да прави подобно нещо.

Така става ли малко по-ясно?

**Comment by Ivan-Tashev** [comment]
Да, **абсолютно** ясно! 
И аз стигнах до подобно собствено демо, след доста проби/грешки...

Разгледах внимателно, твоето репо само мисля че тук в/у @Cacheable анотацията преди 6-ти ред трябва да има @Target(type.METHOD), иначе няма да работи...
https://github.com/luchob/softuni-labs/blob/master/proxies/src/main/java/bg/softuni/proxies/cache/Cacheable.java

Блгодаря за изчерпателния отговор!

**Comment by luchob** [comment]
Затворено след прокси демото.
