### ISSUE TITLE
Проблем с Thymeleaf, когато искам да достъпя къстъм елементи от разширен User клас

### ISSUE THREAD

**Issue by FreshyMc** [luchob/softuni-sept-2021-misc#50]
Привет!
Имам следния проблем разширих User класа, който идва от Spring security и добавих два къстъм елемента вътре в него.
Всичко работи на ниво контролер и сървис. Обаче, когато поискам да достъпя полето fullName от InstamarketUser със следното нещо: https://pastebin.com/uHX75Atb
Както и да пробвам единственото, което този Principal дава е само полето name, което си е празно. Въртях, суках ама не се получава. Може би съм изцяло в грешна посока, но въпроса е как тези къстъм поленца от класа InstamarketUser да са достъпни през Thymeleaf?
Линк към проекта: https://github.com/FreshyMc/InstamarketProject
Лека вечер!

**Comment by Alexander-Gruev** [comment]
Полето в InstamarketUser  се казва  userFullname, а не fullName

**Comment by FreshyMc** [comment]
Прав си допуснал съм грешка при писането на въпроса, пробвах но пак не става за жалост :(

**Comment by luchob** [comment]
Е не ти вярвам. Защото и аз пробвах и става :-) Прилагам доказателствата за моя уважаван admin admin:

<img width="1247" alt="Screenshot 2021-11-15 at 8 56 08" src="https://user-images.githubusercontent.com/10339738/141736250-a80b0635-2c8e-4e47-8d22-c14160d2dfde.png">

**Comment by FreshyMc** [comment]
Ей големи сте хакери признавам ви :) Най-вероятно съм се объркал и много време се чудех защо InteliJ не дава подсказка. Важното е че стана!
