### ISSUE TITLE
Jwt Authorization and securing requests.

### ISSUE THREAD

**Issue by AlexanderNestorov** [luchob/softuni-sept-2021-misc#51]
Здравейте, идеята ми за security за проекта ми е да използвам jwt токен за authorization. Направил съм логиката за логване и регистриране на потребител като login записва user-a в securityContext-a  и връща респонс с токена. Добавил съм Authorization на самите заявки в WebConfig -> configure. Когато тествам в Postman всичко работи добре, освен че заявките работят и с token на логнатия в момента потребител и с token  на потребители които преди за били логнати.(Дори след рестарт на приложението). Предполагам, че това е част от поведението на SecurityContext-a. Въпросът ми е дали това е валидно поведение в практиката?

Линк към проект: https://github.com/AlexanderNestorov/PC-Point

**Comment by luchob** [comment]
Хех, браво :-) Интересен проект.

Това за тоукъните на разлогнатите юзъри е много неприятен въпрос, защото реално няма лесен начин бекенда да разбере, че юзъра се е разлогнал. Сигнатурата на тоукъна е валидна, всичко е ок и докато не изтече expiration date-а му той се валидира успешно. След това става наистина невалиден. Веднъж съм го виждал в доста голям проект този проблем и там тоукъните бяха валидни за по 3 минути. Така че след логаут на юзъра имаше максимално 3 минути... как да го нарека... "window of opportunity" :-) И то въпреки че на identity provider-a тоукъна се изтриваше. Но бекенда няма как да разбере това лесно. Има известен компромис със сигурността, но мисля, че ако тоукъна е достатъчно краткосрочен това е приемливо.

Поздрави,
Л.
