### ISSUE TITLE
Въпрос относно Spring Security

### ISSUE THREAD

**Issue by FreshyMc** [luchob/softuni-sept-2021-misc#52]
В моята апликация имам функционалност за смяна на паролата. Питането ми е как може след като променя паролата да накарам потребителя да излезе от профила си и да се логне отново с новата си парола. Има ли възможност това нещо да стане в конфигурацията на Spring Security с GET mapping request.

**Comment by luchob** [comment]
Здрасти!

Може да го накараш с браузър редирект, обаче това не е твърде сигурно защото може и да не сработи навсякъде. Не съм го ползвал никого, на мисля, че можеш да го логаутнеш програмно използвайки `SecurityContextLogoutHandler`. Кодът би могъл да изглежда като нещо от сорта на:

```
public void logout(HttpServletRequest request, HttpServletResponse response) {        
          Authentication auth = SecurityContextHolder.getContext().getAuthentication();
          if (auth != null) {
              new SecurityContextLogoutHandler().logout(request, response, auth);
          }
  }
```

`request` и `response` сринг инжектира в контролерите.

Поздрави,
Л.
