### ISSUE TITLE
Problem with getting a current logged user field - balance.

### ISSUE THREAD

**Issue by vladikata2535** [luchob/softuni-sept-2021-misc#53]
Здрасти Лъчо, 

Исках да те попитам, понеже ми трябва да си сложа за всеки логнат user горе в nav бара една дивче, което изписва текущия balance на самия logged user. Та как по-точно да му достъпя това поленце balance, за да си го сложа като стойност в html-a, а и също да си го модифицирам като намалям стойността при закупка на продукт или я увеличавам при добавяне на парички.

Поздрави,
Влади

**Comment by luchob** [comment]
Привет!

Ами има най-различни начини, по които можеш да направиш това. Няколко примери:

1. С къстъм user от твоя UserDetailsService. В.ж. например въпроса на колегата - https://github.com/luchob/softuni-sept-2021-misc/issues/50
2. С AOP (довечера) :-)
3. С ModelAttribute в (почти) всеки контролер
4. С отделна fetch заявка в навбара
5. С къстъм [HandlerInterceptor](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/HandlerInterceptor.html) който може да пипа модела след изпълнение
6. ....

:-)

Всички ми изглеждат като работещи решения, избери си някое.

Поздрави,
Л.
