### ISSUE TITLE
Неработещ scheduler 

### ISSUE THREAD

**Issue by Alexander-Gruev** [luchob/softuni-sept-2021-misc#54]
Здравейте, имам един scheduler в package scheduler , който трябва да изтрива кеширането на стойности от базата през определено време, но не работи : https://github.com/Alexander-Gruev/Fitshop

**Comment by amdimov** [comment]
И при мен не става по този начин. Работи само с CacheManager - https://www.baeldung.com/spring-boot-evict-cache

**Comment by luchob** [comment]
Привет банда! В момента няма как да го пробвам, но мисля че сте настъпили една спринг мотичка :-) Почти съм 100% сигурен, че шедюлъра се пуска, но също така мисля, че и няма да работи :-)

Причината е, че в рамките на един компонет (класа `RemoveCacheScheduler`, който е прокси обект) се вика вътрешен анотиран метод. В този случай, анотацията на втория метод не би трябвало да може да бъде прочетена. 

Предполагам, че в шедюлъра трябва да се инжектира сървис, чийто метод трябва да се извика. Демек `evictAllCacheValues` трябва да се премести в сървис, който се инжектира в шедюлъра. Дано не греша, но имам доста сериозно предположение, че е така. Опитай и пиши, ако не съм прав.

Поздрави,
Л.

**Comment by Alexander-Gruev** [comment]
Благодаря ви, мисля че работи. Следващият проблем е, че когато кешира някой продукт, а аз го изтрия, той остава кеширан на фронтенда, но вече не съществува в базата и съответно получавам 404 когато му цъкна details

**Comment by luchob** [comment]
:-) Това вече е съвсем различен проблем, наистина. Ако искаш да кешираш и триеш по ключ, то тогава трябва ключа да участва в кеша, напр:

```
@Cacheable(value = "usersCache", key = "#user.id")
public List<Order> getUserOrders( User user ) {
}

@CacheEvict(value = “usersCache”, key = "#user.id"),
void delete( User user );
```

Или както казах на лекцията - кешовете са супер готино нещо, докато не почнеш да ги ъпдейтваш :P

Поздрави,
Л.

**Comment by Alexander-Gruev** [comment]
При мен кеширането не е по ключ - аз кеширам четирите най-евтини продукта от базата, които показвам на index страницата. Идеята е на всеки два часа да се трие кешът и ако админът е добавил по-евтин продукт той да се покаже като един от тези четири

**Comment by luchob** [comment]
Значи кешът трябва да се трие, и когато админа добави по-евтин продукт :-) Също така, ако се изтрие някой от продуктите. В общи линии - няколко варианта:
1. При всяко едно събитие, дето може да доведе до инвалидиране на кеша се трие целия кеш (лесно)
2. При всяко едно събитие, дето може да доведе до инвалидиране на кеша се обхожда целия кеш и се трие само ако е нужно.
3. Кешът преработва и се прави по id

**Comment by Alexander-Gruev** [comment]
Благодаря ти Лъчо, направих го да чисти кеша при изтриване на продукт. Мисля че за моята логика е по-добре да не се трие при създаване на по-евтин продукт, защото така се губи смисълът от самия scheduler, който чисти кеша на всеки 2 часа
