### ISSUE TITLE
Малко помощ с security

### ISSUE THREAD

**Issue by HristoManov91** [luchob/softuni-sept-2021-misc#55]
Здравей Лъчо.Дали може да погледнеш относно Security частта да ми кажеш как трябва да го направя.
1.В WebSecurityConfiguration е настроено къде имат достъп логнат и не логнат User.В fragments/nav съм направил Manager бутона да се вижда само от User с поне Manager роля и отделно някои под менюта са само за Admin(тях може би трябва в отделен бутон да ги изкарам).Та проблема е че ако напиша самият линк и съм логнат без значение с кой User ми отваря страниците въпреки че имат sec:authorize="hasRole('ROLE_ADMIN')". Може ли да ми обясниш тази защита е просто да се скрива бутона ли само и ако да къде е по-добре да направя защитата в Controller с @PreAuthorize анотация или в WebSecurityConfiguration като на определените страници слагам кой с каква роля може да ги достъпва мисля че имаше такава настройка.
2.Самата @PreAuthorize анотация ако може да и хвърлиш един поглед нали е направена ок в UserController имам предвид че трябва да я сложа и на @Get и на @Patch така ли е правилно? 
Може ако го погледнеш преди лекцията и решиш че е полезно за всички и на нея да го обясниш,Благодаря оставям линк за проекта дано съм успял правилно да си обясня проблема.
https://github.com/HristoManov91/Celio

**Comment by luchob** [comment]
Привет!

Относно първия въпрос бих препоръчал конфигурация в WebSecurityConfiguration, нещо от сорта на:
            `.antMatchers("/products/add").hasRole("MANAGER")`

Причината е, че ми се струва по-удачно (особено при server side rendering) настройките за логнат/нелогнат и ролите да са на едно място в секюрити конфигурацията. Това обаче не винаги е съвсем възможно, предвид 2-я ти use-case.

Там доколкото разбирам, данните може да се виждат и/или променят само от собственика или от администратора, който не е собственик но ролята му позволява това. Така че си поставил напълно правилно Preauthorize и на двете места (get + patch).

Поздрави,
Л.

**Comment by HristoManov91** [comment]
Значи всички страници които са за User с роля Manager или Admin да ги направя с antMatchers в WebSecurityConfiguration а тези които са с 2 условия както е собственик и Admin примерно да ги направя с PreAuthorize анотация?
А иначе като хвърляне на грешки дали така е ок както съм го направил и съответно понеже вече не се вижда stacktrace в самият клиент къде е правилно да се изпраща или запазва този stacktrace,за да може да се види и оправи
