### ISSUE TITLE
Имплементиране на follow/like бутон.

### ISSUE THREAD

**Issue by apostol03** [luchob/softuni-sept-2021-misc#56]
Здравей, Лъчо! Искам да те попитам дали можеш да ми помогнеш с имплементирането на бутон (да кажем follow), който при натискане да запазва съответното follow-нато ентити в профила на user-a. Имах някаква идея, но тя беше да правя допълнителни полета в UserEntity като това ми се стори грешно, а и така или иначе не успях да го направя да работи. Търсих в гугъл, но не можах да намеря подобна информация. 
За реален пример ако от горе стана неясно - бутона Like в YouTube - когато натиснем Like, видеото, което сме харесали отива в Liked Videos - това искам и аз да направя.
Благодаря предварително!

**Comment by luchob** [comment]
Здравей!

Ще опитам :-)

Наистина не е ок с полета в юзъра. Дали не може ли да го направим по подобен начин. В ДБ да има подобни таблици:

users:

| ID   | Name   | Age |
| --- | --------|---- |
|1     | Pesho   | 32   |
|2     | Lucho   | 42  |


videos:

| ID   | URL    | Description |
| --- | -------|------------ |
|1     | http://..| South Park  |
|2     | http://..| Itchy Boots | 

liked_videos:

| ID   | user_id    | video_id |
| --- | -------|------------ |
|1     | 1         |   1  |
|2     | 1 | 2 | 
|3     | 2 | 1 | 

Тук виждаш, че Пешо харесва South Part и Itchy boots, докато Лъчо само Itchy boots. Новото ентити `LikedVideo` може да има полета `UserEntity` и `VideoEntity`.

Не забравяй, че като триеш юзър, трябва да изтриеш харесваните видеа и като триеш видео също.Надявам се да има някакъв смисъл.

Поздрави,
Л.

**Comment by apostol03** [comment]
Благодаря ти много, наистина! Всичко тръгна както исках. Поздрави и до утре! 🍻
