### ISSUE TITLE
Проблем с Thymeleaf

### ISSUE THREAD

**Issue by svilen-tech** [luchob/softuni-sept-2021-misc#57]
Здравейте, искам да изкарам всички потребители в таблица и тази страница само админа да има право да я достъпва. Изкарвам всички регистрирани потребители в table и всеки ред има бутон смени и възможните роли, проблемът ми е, че не успявам да пратя username-ите към контролера, а само ролите, къде бъркам?
https://pastebin.com/Tw99yPMw

**Comment by luchob** [comment]
Привет, доста объркана работа ми се струва :-) Доколкото разбирам, юзърът ти може да има само една роля. В такъв случай е доста подходящо ролите да се опишат в `enum`. Например, разгледай в мобилелеле [UserRoleEnum](https://github.com/luchob/softuni-sept-2021-misc/blob/master/mobilelele/src/main/java/bg/softuni/mobilelele/model/entity/enums/UserRoleEnum.java).

 Тъй, след това е достатъчно 1 DTO, напр:

```
public class UserForAdminDto {
    private String username;
    private UserRoleEnum userRole;
}
```

Thymeleaf-a e подобен на твоя (изпускам таблицата за яснота, не е тествано, само псевдокод):

```
<tr >
        <form th:each="user : ${users}" 
              th:action="@{/admin/change}"
              method="post"
              th:object="${user}">

            <input .... th:field="*{username}" name="name"/>
            ...
            <select th:errorclass="is-invalid" id="role" name="role" class="form-control">
                    <option value="">- Select role -</option>
                    <option th:each="r : ${T(...RoleEnum).values()}"
                            th:text="${r}" th:value="${r}" th:selected="${r} == *{userRole}"
                    >User role</option>
                </select>
            <button type="submit">Change</button>
        </form>
    </tr>
```

Разгледай внимателно темплейта на [добавянето на оферта](https://github.com/luchob/softuni-sept-2021-misc/blob/master/mobilelele/src/main/resources/templates/offer-add.html).

Не забравяй, че когато ползваш  `th:object` синтаксиса не е `${obj.property}`, а е по-скоро `*{property}`. Защо нещо не се попълва може да кажа само ако имам достъп до проекта, който може да сваля и пусна :-)

Надявам се, че тези жокери ще помогнат! Ако не ще мислим натам.

Поздрави,
Л.
