### ISSUE TITLE
i18n не работи правилно

### ISSUE THREAD

**Issue by HristoManov91** [luchob/softuni-sept-2021-misc#58]
Здравей Лъчо.Имам проблем с i18n излизат съобщенията само на български,но не и на английски,дали може да ми помогнеш какво съм пропуснал?
https://github.com/HristoManov91/Celio/tree/main/SellersResults/src/main

**Comment by luchob** [comment]
Привет, може ли малко съдействие? При мен излизат и на двата езика...

<img width="683" alt="Screenshot 2021-11-18 at 8 19 30" src="https://user-images.githubusercontent.com/10339738/142362898-de1a0efa-a5a7-473d-81ea-8152e84bf4fb.png">
<img width="664" alt="Screenshot 2021-11-18 at 8 19 39" src="https://user-images.githubusercontent.com/10339738/142362902-57aafaca-e298-4baa-9e47-b9e3b97cd587.png">

Поздрави,
Л.

**Comment by HristoManov91** [comment]
![Екранна снимка 2021-11-18 101631](https://user-images.githubusercontent.com/73854367/142377794-34d0ebab-248f-47aa-9cd2-b4218ec20a86.png)
![Екранна снимка 2021-11-18 101559](https://user-images.githubusercontent.com/73854367/142377795-6b273306-8519-48bf-b1f0-db96b57bf1a2.png)
Хмм странно от какво може да е...

**Comment by luchob** [comment]
Аз съм с последната версия. 
Едва ли е от спринг. Минава ли заявка по мрежата? С какъв браузър си, ако е Chrome в devtools виждаш ли request/reponse? Сменя ли се URL-то? Ребилднал ли си проекта? С друг браузър работи ли?

**Comment by HristoManov91** [comment]
С edge пробвах не работи иначе аз съм си с chrome
Проекта съм го ребилднал
Url се сменя
Заявката се вижда
Само това по мрежата нещо не ми е ясно как да проверя
![Екранна снимка 2021-11-18 102950](https://user-images.githubusercontent.com/73854367/142380715-45a8bcfa-b296-4a18-b6ec-03ae4a458167.png)
?

**Comment by luchob** [comment]
Хммм, много интересно. Да не би да си експериментирал и вече да има някакво куки? Може ли да пробваш в инкогнито моуд. Много ми е трудно да ти помогна, защото при мен си работи напълно ок. Да не би да имаш нещо некомитнато?

**Comment by HristoManov91** [comment]
В инкогнито мод също не става,всичко е качено освен,че днес довърших целият превод който още не съм качил.Кукито си се праща и ъпдейтва всеки път.Това което се чудя е за en_EN и bg_BG или в UTF-8 стандарта нещо там да нямам проблем спрямо локалните настроики на лаптопа ама не успях да намеря инфо за решение на проблема в нета днес.Надявам се да го кача на Heroku и там да е ок.

**Comment by luchob** [comment]
Това е адски интересно... Защото при мен работи, дори и когато IntelliJ по подразбиране енкодва пропърти файловете в ASCII. Това което би могло да е особено, че преди Java 9 пропърти файловете по подразбиране можеха да съдържат само ASCII, но това вече не е така. Настройва се ето оттук:

<img width="839" alt="Screenshot 2021-11-19 at 16 31 39" src="https://user-images.githubusercontent.com/10339738/142639475-893936d9-c2d8-4f2a-8db4-52a7fe8c1f43.png">

Но ме съмнява това да е проблема, ако енкодинга е проблема ще излязат маймуни просто. Хм... знаеш ли какво, я пробвай тези неща:
1. Опитай да преименуваш bg_BG на de_DE, както и локалите в комбото, да видим да не му е твърде екзотичен този локал.
2. Опитай да чекаутнеш проекта на чисто и да го пробваш (при мен върви всичко на 100%, изобщо не виждам къде може да е проблема)
3. Опитай да активираш в application.yaml DEBUG логинг за org.thymeleaf и за org.springframework.web.servlet.i18n

Така като всичко изглежда 6 и освен това работи при мен ми е доста трудно :-) Пробвах го и на сафари - няма грижи, едва ли е от браузъра.

**Comment by HristoManov91** [comment]
Здрасти мерси за съветите.Пробвах съветите и добавих немски и можех да го избера,но още нямах английски.Незнам от къде ми дойде и преименувах файла с _en окончание то обаче промени и другите и станаха _en_bg _en_de и така работеше.След това редактирах името на другите да си останат _bg и основният файл спря да се вижда в intellij,но си работеше функцията и го има във папката на програмата и ако ми се наложи редакция мога от там да го правя.Само странно е че не се вижда в Intellij.Благодаря отново за съветите.
Иначе имам проблем който не мога да намеря бъга.Като се получава само на админският профил в best bill и bill with most products в profile.Реално в базата самата сметка е от 7 артикула,а в profile ги изписва 21 и съответно и сумата е 3х по голяма.Като го проследих с debug entity-то си идва още от базата с тези данни и реално незнам как става това.Може ли да пробваш защо така се получава ако не се получи от първият път ще трябва няколко пъти да триеш и създаваш базата.
![Екранна снимка 2021-11-20 225229](https://user-images.githubusercontent.com/73854367/142740793-2b6bab10-7764-4298-a122-f2172ff56b71.png)

**Comment by luchob** [comment]
Привет! 

А какво трябва да направя за да пресъздам бъга, трудно ми е да се ориентирам. В момента като чекаутна всичко и направя инициализация  няма sales, а контролера за правене на sale не работи.

Но! Всъщност, това няма значение защого аз съм 99.99% сигурен какъв ти е проблема. Това е нещо, с което искам да почна във вторник лекцията, защото е много тънко. `UserEntity`-то ти е неправилно построено, и оттам мисля че ти идват проблемите. Пресъздава се точно за админ и е точно x3 защото админа има  роли :P

```   
private List<SaleEntity> sales;
private Set<UserRoleEntity> roles = new LinkedHashSet<>();
```

Тези две неща са ти с EAGER FETCH. Ако обаче направиш roles да бъде List, а не Set Spring ще те изненада. Ще получиш:

`org.hibernate.loader.MultipleBagFetchException`

Историята е много дълга, но спринг няма да ти позвали да имаш 2 list-а (OneToMany или ManyToMany) с EAGER FETCH, защото не може да направи коректна заявка за да извлече и двете. Това се "оправя" по възможно най-грешния начин ако направиш променливата да бъде Set вместо List, както ти си направил. Направо си е бомба със закъснител, както си видял. Тогава ако имаш правилно имплементирани eqauls и hashcode може и да сработи на глед коректно, но въпреки това hibernate ще направи cross join отдолу. Т.е. - пълна щета. Виж отговора на Vlad Mihalcea в [този въпрос](https://stackoverflow.com/questions/4334970/hibernate-throws-multiplebagfetchexception-cannot-simultaneously-fetch-multipl) и ще стане по-ясничко.

Решението би могло да е lazy fetch на колекциите в `UserEntity` и съответните Transactional анотации, за да не гърми. Абе нагазил си в по-дълбоките води, браво :-)

Поздвари,
Л.

**Comment by HristoManov91** [comment]
Да хвърляше ми тази грешка,но като търсех как да я оправя явно не съм прочел че това е най-лошият вариянт :D сега ще си го оправя,благодаря за помоща и чакам лекцията с нетърпение

**Comment by HristoManov91** [comment]
За Vlad Mihalcea сега му разгледах профили и сайт той не е случаен :D даже след седмица има семинар 4ри дневен за java

**Comment by luchob** [comment]
Влад е автор на една от най-сериозните книги за Java Persistance, Java шампион и един от най-добрите hibernate експерти. Изобщо не е случаен :-)

**Comment by HristoManov91** [comment]
Сега като съм си написъл в CV-to в skill Java сега мисля че от Java знам 1% сигурно :D

**Comment by HristoManov91** [comment]
А съвет да ми дадеш че от два дни съм в дилема.Искам да пазя седмични и месечни резултати,като нали всеки понеделник и всяко първо число на месеца ще се извикват с scheduling и cron през ноща понеже е тежка операция.Но сега проблема ми е как и къде да ги запазя?Трябва ли от тях да създам обект за всеки User- UserWeekResult и UserMonthResult и за 2те entity-ta да има repo и service и да се пазят в базата в отделна таблица или някакъв по-добър подход може да ми кажеш да използвам.Те ще се използват само за view в рест контролер.

**Comment by HristoManov91** [comment]
Отностно предният проблем понеже не успях да се справя с Lazy и Transaction изпробвах това:
@ManyToMany(fetch = FetchType.EAGER)
    @Fetch(value = FetchMode.SUBSELECT)
и то свърши работа.Иначе изчетох всичко с коментарите и ми е малко сложно да разбера,надявам се другиден като пообясниш малко с твоя помощ да ми се избистрят нещата.

**Comment by luchob** [comment]
Здрасти!

Относно съвета - бих предпочел отделни ентитита за статистиката. Те може да са две, както си казал, или още по-добре да е едно + типа на статистиката - MONTH или WEEK.  А fetch е хибернейтска анотация. Надявам се утре да хвърлим доста повече светлина върху EAGER, LAZY и Set vs. List.

Поздрави,
Л.

**Comment by HristoManov91** [comment]
Благодаря за всичко :)
