### ISSUE TITLE
Swap items

### ISSUE THREAD

**Issue by MurAhm** [luchob/softuni-sept-2021-misc#59]
Здравей, Лъчо.  Идеята е подобна на Friend Request във Facebook, но става въпрос за размяна на някакви предмети. Да речем, че user1 е добавил някакъв предмет,  user2 го вижда и иска да го размени за негов предмет. Цъка на бутон SWAP и при user1 отива заявка. User1 може да одобри или откаже. В това време заявката при user2 е Pending и докато чака user1 да реши, user 2 има възможност да натисне Cancel и да прекрати заявката. При одобрение от user1, двата предмета се разменят. Може ли да ми дадеш насоки как това би станало  със Spring?

**Comment by luchob** [comment]
Хей, привет!

Ами тук изобщо не става въпрос за Spring, по-скоро става въпрос как да си организираме обектите в ДБ. Да речем, че Лъчо има кон, Пешо кокошка и Лъчо иска да размени кон за кокошка. Ето как виждам първоначалната ситуация.

`UserEntity`:

| ID      | Name |
| ----- | ------ |
| 1      | Лъчо       |
| 2   | Пешо        |

`ObjectEntity`

| ID      | Description | Owner_ID |
| ----- | ------ | ------ |
| 1      | Кон       |1 |
| 2   | Кокошка        |2|

Имаме и една празна табличка, да речем:

`SwapRequestEntity`

| ID      | offer_object_id | wanted_object_id|
| ----- | ------ |----------|

Лъчо натиска едно бутонче, минаваме през контролер и сървис и се получава един пендинг рекуест:

`SwapRequestEntity`

| ID      | offer_object_id | wanted_object_id|
| ----- | ------ |----------|
|1        | 1          |     2          |

Това нещо се вижда в акаунта на Пешо. Ако той не се съгласи, може просто да се изтрие рикуеста (или да се добавят още колонки, с които да се маркира като невалиден). Ако се съгласи обаче, трябва да се изтрие отново, както и да се променят собствениците на предметите:

`SwapRequestEntity`

| ID      | offer_object_id | wanted_object_id|
| ----- | ------ |----------|
|1        | 1          |     2          |

| ID      | Description | Owner_ID |
| ----- | ------ | ------ |
| 1      | Кон       |2 |
| 2   | Кокошка        |1|

Освен това трябва да се обработят следните събития:

1. Изтриване на обект - трябва да се изтрият всички swap request-и
2. Успешна размяна - трябва да се изтрият всички други swap request-и, тъй като реално вече собствениците на обектите са други.

Още по интересно става, ако един юзър иска да размени 1 негов предмет за няколко предмета на друг юзър ;-)

Та тъй - това ми е идеята, останалото е контролерчета и сървисчета ;-)

Поздрави,
Л.

**Comment by MurAhm** [comment]
Много ти благодаря!
