### ISSUE TITLE
Проблем с изпълнение на app.js

### ISSUE THREAD

**Issue by stefangulev** [luchob/softuni-sept-2021-misc#60]
Здравейте,

Опитвам се да изпълня script в следното view, с цел изпълняването на fetch в JS файл: https://pastebin.com/dwf7vUv5

Script-а се намира на в следната директория: 
![image](https://user-images.githubusercontent.com/69120680/142473515-c394f195-e450-4870-ae43-6c907defde34.png)

Независимо от съдържанието на скрипта, при достъпване на view-то, в конзолата на браузъра получавам следния еrror:
![image](https://user-images.githubusercontent.com/69120680/142473658-5459311d-56bf-4a6c-a599-27bd903bb020.png)

Някакви идеи? Благодаря предварително!

**Comment by luchob** [comment]
Пронто :-)

Идеи имам само 1 ;-) URL-то е грешно, оттам и 404 - not found. 

Думичката `static` не трябва да фигурира в URL-то, тоест само `http://localhost:8080/js/app.js` е правилното URL. Тези неща, които са в `resources\static` в структурата на проекта са т.нар. статични ресурси и са достъпни в руута на сървъра, т.е. `http://localhost:8080/`. По същата логика `http://localhost:8080/resources/static/js/app.js` е още по-неправилно :-) Правилно е `http://localhost:8080/js/app.js`.

Поздрави,
Л.

**Comment by stefangulev** [comment]
Проработи, много благодаря!
