### ISSUE TITLE
Quick Mock testing Question.

### ISSUE THREAD

**Issue by AlexanderNestorov** [luchob/softuni-sept-2021-misc#62]
Здравейте, тествам един от REST контролерите си, чрез Mocking, по следния начин:
https://github.com/AlexanderNestorov/PC-Point/blob/master/src/test/java/com/example/pcpoint/controller/LocationControllerTest.java

Въпросът ми е, дали след като тествам Controller layer-a, дали трябва да тествам Repository и Service layers, ако в Controller тестовете използвам съответните Service и Repository имплементации?

**Comment by luchob** [comment]
Привет! 

Два отговора + 1 OFFTOPIC. Ако въпроса е свързан с изпита, в условието пише:

```
Write tests (Unit & Integration) for your logic, services, repository query methods, helpers, etc.
You should have at least 60% coverage on your business logic.
```

Т.е. там ще ти гледат коуд ковириджа, който се вдига доста дори от интегрейшън тестове, дето почти нищо смислено не правят :-) Т.е. за изпита си ок, стига да имаш и някой Unit test. Абе трябва да имаш от всичко по нещо и ковиридж 60%.

Какво става в добрата практика обикновено е по-различно. По-принцип в идеалния вариант се стремим да постигнем максимален ковиридж с юнит тестове и да имаме възможво по-малко интегрейшън тестове. Т.нар. тестова пирамида. Защото:

- юнит тестовете са много бързи
- юнит тестовете не са толкоз трошливи и по-лесно се разбира какво не е наред

Разбира се, интегрейшън тестовете и E2E също са полезни, стига да не се прекалява с тях. Работил съм по проект, който се тества за няколко дни (с HTML клик тестове) :-) и да излезе нова версия успешно си беше празник, ако се случи веднъж на месец.

Сега за оффтопика - разгледал ли си анотацията WithMockUser?

Поздрави,
Л.
