### ISSUE TITLE
Проблеми с REST при POST request от клиентска страна.

### ISSUE THREAD

**Issue by FreshyMc** [luchob/softuni-sept-2021-misc#63]
Здравей Лъчо!
Имам проблем със Rest Controller, когато пускам POST заявка към път /api/offers/search във OfferRestController връща отговор 403 - Forbidden. Та гледах и се сетих, че ми трябва csrf поле, сложих го и със JS взех името му и стойността след което го пращам като HTTP Header. Е да ама не пак същата работа, Spring си ме резва и това си е, а не ми се иска да премахвам csrf защитата.
Файла, в който е REST fetch api е home.js, като е сложен във home.html страницата. Благодаря предварително голям препъни камък стана :-), желая страхотен уикенд.
Линк към проекта: https://github.com/FreshyMc/InstamarketProject
Поздрави!

**Comment by luchob** [comment]
Eee, чак пък препъни камък :-) Просто се каляваш в битка, ако беше лесно всички щяха да са топ спринг гурута. Вместо това са обикновени хора като нас :P

CSRF тоукъна има различни имена, когато го пращаш като параметър на форма (_csrf) и когато, както теб - като http header (X-CSRF-TOKEN). :-)

Опитай с това:
```
 <input type="hidden" th:name="${_csrf.headerName}" th:value="${_csrf.token}" id="searchCsrf">
```

Утре ще е планинската част на уикенда, днес - мизерия в Сф.

Поздрави,
Л.
