### ISSUE TITLE
Security and REST

### ISSUE THREAD

**Issue by felin-dev** [luchob/softuni-sept-2021-misc#64]
Здравей Лъчо, мъчих се бая време да изпратя POST заявка към рест контролера ми и винаги ми връщаше 403 forbidden, а ако направя същото, само, че с GET работи. Забелязах, че това става заради csrf и го деактивирах за да може да ми работят заявките. Има ли някакъв начин да се оправи без да деактивирам csrf в конфигурацията на SpringSecurity? Благодаря за отделеното време и приятен ден/вечер.

**Comment by luchob** [comment]
Здрасти, Мони!

Виж, колегата май се е справил ;-) https://github.com/luchob/softuni-sept-2021-misc/issues/63
Това би трябвало да ти помогне?

Поздрави,
Л.

**Comment by felin-dev** [comment]
Пробвах го но ми даде, че headerName е нъл, вместо това направих мапинг за поискване на токен и преди да пратя заявката взимам токен и го прикачам. https://pastebin.com/MsKLhCAP
