### ISSUE TITLE
JS Fetch / Other type of Post method in JS

### ISSUE THREAD

**Issue by Vellani** [luchob/softuni-sept-2021-misc#65]
Здравейте,

От известно време се опитвам да направя каквато и да е JS Fetch, Ajax, Jquery  POST заявка към сървъра, но без успех.
Специално за Fetch използвам 

```
let response = await fetch('/profile/admin/save', {
            method: 'POST',
            credentials: 'include',
            headers: {
                'Content-Type': 'application/json;charset=utf-8'
            },
            body: JSON.stringify( Data )
 });
```
Разбира се url-то е защитено от Spring Security, съответно както за unauthenticated, така и unauthorized user, който не е админ.
На други места в проекта спокойно правя $.getJSON заявки без проблем, но тук ми дава 403 Forbidden.
На дебъг ниво виждам, че сървъра разпознава успешно потребителя с правилните cookies.

Благодаря предварително!

**Comment by luchob** [comment]
Добър вечер!

Проблемът е в CSRF тоукъна, който липсва в заявката ти. Други колеги имаха подобна драма, не си сам. 

Виж тук - https://github.com/luchob/softuni-sept-2021-misc/issues/63 Проблемът е разрешен и има код за надникване.
И същия въпрос още веднъж - https://github.com/luchob/softuni-sept-2021-misc/issues/64

Допускам, че това би трябвало да ти помогне.;

Поздрави,
Л.
