### ISSUE TITLE
Problem with Rest Api

### ISSUE THREAD

**Issue by vladikata2535** [luchob/softuni-sept-2021-misc#66]
Здрасти Льчо, 

Имам две таблички за компютри и за телефони и искам да ги визуализирам чрез Rest Api. Как точно трябва да стане това? Трябва да се връщат две ResponseEntity<List<Computers>> и ResponseEntity<List<Phones>> на един route ли ? И в JS трябва да имам два пъти fetch или как точно трябва да стане, защото ти си го направил с една колекция, а при мен са две и се счупих малко.

Поздрави, В.

**Comment by luchob** [comment]
Привет! 

Няма проблеми да са две колекциите, просто трябва да имаш 2 пъти извикване с fetch. Да са на един route - не знам конкретика и не може да се изкажа. Ако и компютрите и телефоните са просто ProductEntity, то е удачно да е 1 път с някакви query параметри, например - намиране на продукти по тип. Ако са ComputerEntity и PhoneEntity то е удачно да са два пътя.

Поздрави,
Л.
