### ISSUE TITLE
HttpServletRequest.getParameter() always returning null.

### ISSUE THREAD

**Issue by AlexanderNestorov** [luchob/softuni-sept-2021-misc#67]
Здравейте, реших да имплементирам interceptor който при извикване на register заявка от UserController да изпраща мейл за успешна регистрация.

Request: 
https://github.com/AlexanderNestorov/PC-Point/blob/master/src/main/java/com/example/pcpoint/model/request/user/RegisterRequest.java

Controller: 
https://github.com/AlexanderNestorov/PC-Point/blob/master/src/main/java/com/example/pcpoint/controller/UserController.java

WebConfig:
https://github.com/AlexanderNestorov/PC-Point/blob/master/src/main/java/com/example/pcpoint/config/WebConfig.java

Interceptor:
https://github.com/AlexanderNestorov/PC-Point/blob/master/src/main/java/com/example/pcpoint/controller/email/EmailInterceptor.java

Въпросът ми е защо .getParameter() винаги връща null , като му изпращам коректна заявка, в чийто JSON присъства поле 'email'?
Мисля, че не е проблем от конфигурацията тъй като съобщението се изпраща само на определения за това ендпойнт.

**Comment by luchob** [comment]
Здравей!

Как да го обясня... Добре, да опитам.  Както си личи от пакета, `javax.servlet.http.HttpServletRequest` не е част от Spring Framework-a и е една обектна абстракция на HTTP заявка. Учили сме за HTTP в първата част, ще те сваля
малко по-надолу на ниво 5 от OSI модела ;-)

Eто ти една POST заявка с JSON, нещо като това което ти правиш:

```
POST /echo/post/json HTTP/1.1
Host: reqbin.com
Accept: application/json
Content-Type: application/json
Content-Length: 81
      
{
  "Id": 78912,
  "Customer": "Jason Sweet",
  "Quantity": 1,
  "Price": 18.00
}
```

Ето още една, този път на събмитната форма, с две полета input полета - key1 и key2:

```
POST /echo/post/form HTTP/1.1
Host: reqbin.com
Content-Type: application/x-www-form-urlencoded
Content-Length: 23
      
key1=value1&key2=value2
````

А сега ето и GET с query параметър:

```
GET /genapp/customers?name=Lucho 1 
Host: www.example.com
```

Значи, тези парченца текст се съдържат в HttpServletRequest и неговите методи, един от които ти използваш: `getParameter`. Да видим какво пише в документацията на този метод:

`For HTTP servlets, parameters are contained in the query string or posted form data.`

Т.е. няма как да го пуснеш в JSON обект и да очакваш да се вземе от `getParameter`.

Поздрави,
Л.
