### ISSUE TITLE
Сложен казус относно методи за вадене на данни от JPA Repos

### ISSUE THREAD

**Issue by FreshyMc** [luchob/softuni-sept-2021-misc#68]
Привет Лъчо!
Оказах се в доста забъркано положение. Имам следният проблем, на началната си страница имам формуляр за търсене на обяви **по ключова дума**, **категория на обявата**, търсене в диапазон на две суми (минимална за обява и максимална), също така **дали обявата има free shipping** и дали **е добавена в любими**.  Това, което е с bold шрифт е имлементирано успешно, проблема дойде, когато искам да филтрирам по цените. Имах следните идеи:

1. от всеки метод, който връща резултат преди да го мапна към OfferDTO да го филтрирам със стрийм апи-то. Не го направих, защото ми се вижда лоша идея. Тъй като е най-хубаво тези филтрации да стават на ниво бази данни.
2. Да ползвам нещо от сорта на Criteria Queries обаче и това не виждам практически как да стане.

Проблемът се намира във OfferServiceImpl и метода където е цялата логика за търсене досега е в searchOffers.
Ето и линкче към проблема: https://github.com/FreshyMc/InstamarketProject/blob/master/src/main/java/com/example/instamarket/service/impl/OfferServiceImpl.java
Благодаря предварително!
Поздрави!

**Comment by luchob** [comment]
Хихи :-) Добра да е!

Тъй, по идеите ти:

1. Много, много лоша идея. Защото за всеки критерий ще имаш по един сърч и после ще правиш чудесии в Java, милиони. Това нито ще работи като перформънс, нито ще можеш да го тестваш, нито да го поддържаш. Абе няма да стане, не мисли в тази посока :-)
2. Тук пък защо да не виждаш практически как ще стане? Точно това е решението и точно това се прави. Проблемът е, че наистина е кораво. Но... аз ще ти дам малко жокери под формата на код и болката би трябвало да е намале. Но пак ще боли :-) Нека опитаме.

Стъпка 1) Репозиторито трябва да е и `JpaSpecificationExecutor<Offer>`. Ето как ще изглежда:

```
public interface OfferRepository
    extends JpaRepository<Offer, Long>, JpaSpecificationExecutor<Offer>
```

Стъпка 2) Трябва да създадеш имплементация на `Specification<Offer>`. Съвсем набързо нахвърлях една (не ме вини че кода не е перфектно чист :-) ), която търси по:

- категория (опционално)
- минимална цена (опционално)
- дали е във favorites (опционално)

Ето я:

```
public class OfferSearchSpecification  implements Specification<Offer> {

  private static final String CATEGORY = "offerCategory";
  private static final String PRICE = "price";

  private final SearchServiceModel searchServiceModel;

  public OfferSearchSpecification(
      SearchServiceModel searchServiceModel) {

    this.searchServiceModel = searchServiceModel;
  }

  @Override
  public Predicate toPredicate(
      Root<Offer> root,
      CriteriaQuery<?> query,
      CriteriaBuilder criteriaBuilder) {

    Predicate p = criteriaBuilder.conjunction();

    if (searchServiceModel.getCategory() != null) {
      p.getExpressions()
          .add(criteriaBuilder.equal(root.join(CATEGORY).get("category"),
              searchServiceModel.getCategory()));
    }

    if (searchServiceModel.getMinPrice() != null) {
      p.getExpressions().add(
          criteriaBuilder.and(criteriaBuilder.greaterThan(root.get(PRICE), searchServiceModel.getMinPrice())));
    }

    if (Boolean.TRUE.equals(searchServiceModel.getFavouriteOffer())) {
      Subquery<WishList> subQuery = createSubquery(
          root, query,
          criteriaBuilder
          );
      p.getExpressions().add(criteriaBuilder.exists(subQuery));
    }

    return p;
  }

  private Subquery<WishList> createSubquery(
      Root<Offer> root,
      CriteriaQuery<?> query,
      CriteriaBuilder cb
  ) {
    Subquery<WishList> subquery = query.subquery(WishList.class);
    Root<WishList> subqueryRoot = subquery.from(WishList.class);
    subquery.select(subqueryRoot);

    Predicate conditions = cb.and(cb.equal(root.get("id"), subqueryRoot.get("offer")));

    return subquery.where(conditions);
  }
}
```

След това отиваш и изтриваш всичко от сървиса :-) и метода започва да изглежда така:

```
    @Override
    public Page<OfferDTO> searchOffers(int pageNo, int pageSize, String sortBy, SearchServiceModel model, String username) {
        Pageable pageable = PageRequest.of(pageNo, pageSize, Sort.by(Sort.Direction.DESC, sortBy));
        return offerRepository.findAll(
            new OfferSearchSpecification(model),
            pageable
        ).map(this::asOffer);
    }
```

И ей го на финалния резултат като куери в конзолата:

```
select
        offer0_.id as id1_10_,
        offer0_.created_at as created_2_10_,
        offer0_.deleted as deleted3_10_,
        offer0_.description as descript4_10_,
        offer0_.modified_at as modified5_10_,
        offer0_.offer_category_id as offer_ca8_10_,
        offer0_.price as price6_10_,
        offer0_.seller_id as seller_i9_10_,
        offer0_.shipping_type_id as shippin10_10_,
        offer0_.title as title7_10_ 
    from
        offers offer0_ 
    inner join
        categories category1_ 
            on offer0_.offer_category_id=category1_.id 
    where
        category1_.category=? 
        and offer0_.price>0 
        and (
            exists (
                select
                    wishlist2_.id 
                from
                    wishlist wishlist2_ 
                where
                    offer0_.id=wishlist2_.offer_id
            )
        ) 
    order by
        offer0_.created_at desc limit ?
```

Дотук с добрите новини... Лошата е, че трябва да го донапишеш :P 

Поздрави,
Л.

**Comment by FreshyMc** [comment]
Ехаааа, ето точно това търсех! Присветна ми пред очите! Лъчо ти си велик!

**Comment by luchob** [comment]
:-) При репотата или в подпакет при репозиторитата.

Поздрави,
Л.
