### ISSUE TITLE
Проблем със security login 

### ISSUE THREAD

**Issue by dimitar1997** [luchob/softuni-sept-2021-misc#69]
Опитва се да рефакторирам изпитната задача от миналия курс и въпреки, че в базата имам потребители, при опит да се логна ми дава грешка, като го дебъгвах ми намира потребителя, но до там.
Това е кода - https://github.com/dimitar1997/batttleShip

**Comment by luchob** [comment]
Хей Митко, здрасти!

Виж какво направих - пуснах ти проекта и погледнах в девтуулс събмита на формата:

<img width="910" alt="Screenshot 2021-11-24 at 18 53 22" src="https://user-images.githubusercontent.com/10339738/143281806-ac145a10-bf15-44d4-8d90-049206f8e0bc.png">

Веднага се забелязва, че паролата я няма в параметрите, някъде е изчезнала и не излиза от браузъра. Това става, когато инпута ти няма атрибут `name`. Трябва да го оправиш, например ето така:

```
<input                            type="password"
                                       id="password"
                                       name="password"
                                       ...>
```

Надявам се да помогне това.

Поздрави,
Л.

**Comment by dimitar1997** [comment]
Точно това беше проблема. Благодаря много!
