### ISSUE TITLE
Spring валидира viewModel вместо bindingModel

### ISSUE THREAD

**Issue by kossyo** [luchob/softuni-sept-2021-misc#7]
Здравейте,

От два дни се мъча да разбера защо Spring валидира viewModel, вместо bindingModel, в резултат на което не ми връща грешките от формата. Ето линк към репозиторито ми: https://github.com/kossyo/mobilele. Прикачам документ с test case и обяснение. Моля за помощ!

Предварително благодаря!

Поздрави и хубав ден,

Константин Коев

[zov_za_pomosht_mobilele.docx](https://github.com/luchob/softuni-sept-2021-misc/files/7261004/zov_za_pomosht_mobilele.docx)

**Comment by luchob** [comment]
Здрасти, Косьо!

Нека да опитаме с един жокер преди всичко, например [този](https://github.com/luchob/softuni-music-db/blob/master/src/main/java/bg/softuni/musicdb/web/AlbumController.java)

И да се опитаме да опростим нещата. 

Стъпка 1) Да добавим модел атрибут, например:
```
 @ModelAttribute("albumAddBindingModel")
  public AlbumAddBindingModel createBindingModel() {
    return new AlbumAddBindingModel();
  }
```

В твоят случай ще е празен байндинг модел на офертата.

Стъпка 2) Да добавим детайлна страничка, например:

```
@GetMapping("/details/{id}")
  public String details(@PathVariable Long id, Model model){

    AlbumViewModel albumViewModel = albumService.findById(id);

    model.addAttribute("album", albumViewModel);

    return "details";
  }
```

В твоя случай ще е офертната страничка с някакъв view model/dto.

Стъпка 3) POST заявката за събмит на формата, както и GET за показване на грешките:
```
@GetMapping("/add")
  public String addAlbum(Model model) {

    model.addAttribute("artists",
            artistService.findAllArtists());

    return "add-album";
  }

  @PostMapping("/add")
  public String addAlbum(@Valid AlbumAddBindingModel albumAddBindingModel,
      BindingResult bindingResult,
      RedirectAttributes redirectAttributes,
      @AuthenticationPrincipal UserDetails principal) {


    if(bindingResult.hasErrors()){
      redirectAttributes.addFlashAttribute("albumAddBindingModel", albumAddBindingModel);
      redirectAttributes
              .addFlashAttribute("org.springframework.validation.BindingResult.albumAddBindingModel", bindingResult);

      return "redirect:add";
    }


    AlbumServiceModel albumServiceModel = modelMapper.map(
        albumAddBindingModel,
        AlbumServiceModel.class);

    albumServiceModel.setUser(principal.getUsername());

   albumServiceModel.setReleaseDate(albumAddBindingModel
           .getReleaseDate().atStartOfDay(ZoneId.systemDefault()).toInstant());


    albumService.createAlbum(albumServiceModel);

    return "redirect:/home";
  }
```

В твоя случай ще са два простички POST/GET mapping-и.

Пиши ми дали примера ти изглежда разбираем и ако не е в събота ще го направим конкретно в твоя проект.

Поздрави,
Л.

**Comment by kossyo** [comment]
Здравей, Лъчо!

Много благодаря за бързия отговор. Твоят пример ме наведе на размисли и след няколко часа намерих проблема. Беше съвкупност от няколко неща, но мисля, че най-важното беше, че в html формата бях сложил th:object="bindingModel", за да си попълвам селект менютата със стойности. Струва ми се обаче, че findErrors се влияе от това и почва да търси грешките в bindingModel-а, понеже съм го сложил в th:object. Имаш ли идея дали наистина му е такова поведението?
Може и да се заблуждавам и да е било нещо друго :)

Благодаря и хубав ден!

Поздрави,
Косьо

**Comment by luchob** [comment]
Здрасти!

Ами... трябва да е bindingModel-a там. Утре (живот и здраве) ще видим как стават нещата, ще има и още малко теория по въпроса.

Поздрави и до утре!

**Comment by kossyo** [comment]
Разбрах го по трудния начин :) Благодаря отново и лека вечер!
