### ISSUE TITLE
Стартиране на приложението

### ISSUE THREAD

**Issue by SantanaSJ** [luchob/softuni-sept-2021-misc#70]
Здравей,
Имам проблем със стартирането на приложението.

<img width="958" alt="Untitled1" src="https://user-images.githubusercontent.com/63861416/143272509-945ba0f8-f6e8-4ffe-ab4e-363324a42fe9.png">

това е Security Configuration. 
https://github.com/SantanaSJ/Problem

Като закоментирам този ред - antMatchers("/", "/users/login", "/users/register").permitAll(). - ме препраща към, доколкото разбирам, spring security login page. В main класа бях добавила @SpringBootApplication(exclude = { SecurityAutoConfiguration.class }), но тогава получих тази грешка - A component required a bean of type 'org.springframework.security.config.annotatiom.ObjectPostProcessor', така че го махнах.

Дали може да ми дадеш насоки къде може да е проблема?

Благодаря

**Comment by luchob** [comment]
Здравей!

Да, ще се опитам да помогна, но може ли да видя целия проект по някакъв начин. 

От тази информация, която ми даваш мога единствено да _гадая_, че линковете ти към статичните ресурси в HTML-a са грешни по един или друг начин. Най-подозрителни са ми css линковете, които имаш в страницата. Допускам, че са объркани, браузъра прави рекуест към нещо, което дефакто е забранено и вместо css получава дерирект 302 към логин страницата. 

Поздрави,
Л.

**Comment by SantanaSJ** [comment]
Ето линк към проекта. Всичко си работеше, нещо добавих в security и май от тогава нещата се объркаха и почнах отначало в търсене на проблема. Като закоментирам Security папката и всичко се зарежда.
https://github.com/SantanaSJ/System

**Comment by luchob** [comment]
Здравей пак!

Така е много по-лесно. Ето какъв е проблемът. Това нещо:

```
requestMatchers(PathRequest.toStaticResources().atCommonLocations()).permitAll()
```

Ти дава достъп до сатични ресурси на т.нар. "сандартни" места, а именно:

```
/css/**
/js/**
/images/**
/webjars/**/favicon.*
/*/icon-*
```

Обаче, в хедъра на хоум страницата си ти имаш достъп до място на статичен ресурс, което не се води за "стандартно". Това е `assets`:

```
    <link href="assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
```

Когато браузъра направи заявка към някое от тези URL-та, които си дала за да си дръпне css, напр:

```
http://localhost:8080/assets/vendor/aos/aos.css
```

Spring проверява дали да даде достъп до урл-то в секюрити конфигурацията и попада на това правило:

```
        antMatchers("/**").authenticated().
```

Просто защото не match-ва никое друго правило преди това.

Казва си - аха, не е разрешен достъпа и следователно трябва редирект към логин страницата (която все още не съществува в проекта ти) => 404. И т.н., и т.н.

Най-лесният начин да го оправиш е да добавиш `/assets/**` в конфигурацията:

```
   antMatchers("/assets/**", "/", "/users/login", "/users/register").permitAll().
```

Тогава ще сработи. Но много по-добре е да си поместиш тези "асети" в "стандартните" директории и да ползваш thymeleaf за да генерираш линкове.

Надявам се, това да помогне :-)

Л. 

<img width="1207" alt="Screenshot 2021-11-24 at 20 52 46" src="https://user-images.githubusercontent.com/10339738/143298213-7b617550-4287-4e7e-a86e-c095fbbff361.png">
