### ISSUE TITLE
Още мъки със Criteria Builder API

### ISSUE THREAD

**Issue by FreshyMc** [luchob/softuni-sept-2021-misc#71]
Здравей Лъчо!
Благодарен съм за жокерите, които ми даде. Хем си викам, че разбрах нещата и ето пак проблемче :-) Та проблема е в метода createSubquery в класа OfferSearchSpecification искам като се селектират нещата от WishList repo-то да има една WHERE клауза, която да премахне нещата, които не са в списъка любими на потребителя, а това се определя от полето isRemoved в WishList класа. Грешката, която ми дава е, че не намира полето isRemoved, което взимам от subqueryRoot и другото е, че го търси в BaseEntity по някаква странна причина.
Ето линкче: https://github.com/FreshyMc/InstamarketProject/blob/master/src/main/java/com/example/instamarket/repository/specification/OfferSearchSpecification.java
Благодаря предварително!
Поздрави!

**Comment by luchob** [comment]
Здрасти! 

Напълно основателно гърми. И аз не го виждам това пропърти isRemoved. Виждам само пропърти което се казва **removed** и се записва в някакво си там поле isRemoved :-) :-) Полето можеше да се казва дори и `iHateJPAAnnotationsOnMethodLevel` :-)

```
 public boolean isRemoved() {
        return isRemoved;
    }

    public WishList setRemoved(boolean removed) {
        isRemoved = removed;
        return this;
    }
```

Виждаш ли колко все по-хубаво става да си слагаш анотациите върху полетата, а не върху методите :-) Не мога да изляза все още на глава с Чочо по този въпрос, но все пас мисля, че е почнал да узрява за това :) Може би и ти също :)

Поздрави,
Л.

**Comment by FreshyMc** [comment]
Върху това можеше да се взирам с дни и пак нямаше да осъзная, че в това е проблема. А за тази практика за анотациите наистина ми хареса от Чочо. Само може да се учим от твоята мъдрост Лъчо! Благодаря!
