### ISSUE TITLE
Question about scheduler in service

### ISSUE THREAD

**Issue by vladikata2535** [luchob/softuni-sept-2021-misc#72]
Здрасти Лъчо, 

Как мога да взема логнатия user от някой ServiceImplementation, защото искам чрез Scheduler да добавям в логнатия user данни?

Поздрави В.

**Comment by luchob** [comment]
Здрасти!

Ами... доколкото разбирам въпроса ти, в него има нещо гнило. В шедюлър не можеш да вземаш логнат юзър, защото няма такъв. Шедюлърът се изпълнява в бекграунд нишка, независимо дали има 1-2-5-10 или пък 0 логнати юзъри. Просто няма никаква връзка. Да речем, той може да се стартира в 2 часа през нощта, когато теоритично на сайта няма никой и да свърши някаква работа. Но може и да се стартира в момент, в който има 1000 логнати юзъри.

Поздрави,
Л.

**Comment by vladikata2535** [comment]
Ами исках да реализирам нещо като купони, които притежава всеки един user, и като примерно в приложенията на магазините да се изтриват и да се добавят нови купони примерно през един ден, но като гледам май няма да стане и ще го мисля по друг начин.

**Comment by luchob** [comment]
Защо пък да не стане? Доколкото разбирам искаш да даваш купони на юзър, стига той да е или да е бил логнат преди Х часа/минути. Може да добавиш една колонка last logged in или last active или last order и т.н. и според стойността в нея да раздаваш купони.

**Comment by vladikata2535** [comment]
Прав, си благодаря за съвета, ще го обмисля :)
Лека вечер и много здраве ти желая!
