### ISSUE TITLE
question about interceptors

### ISSUE THREAD

**Issue by vladikata2535** [luchob/softuni-sept-2021-misc#73]
Здрасти Лъчо отново,

Искам да те попитам с какъв интерсептор горе долу трябва да прихвана рекуеста, когато user се регистрира, за да си пазя някакво инфо в базата примерно - User Pesho registered sucessfully at LocalDateTime.now().
И как горе долу да прихвана точния рекуест на регистрацията?
Мерси предварително!

Поздрави В.

**Comment by luchob** [comment]
Привет!

Мисля, че интерсептора е доста неподходящо решение за целта. От всички неща които сме учили предлагам два варианта:

1. С къстъм Ивент
2. С извикването на някакъв код в метода с регистрацията :))) Old school

Единственото предимстно на 1) е, че ще изглеждаш по-куул на изпита :))

Поздрави,
Л.
