### ISSUE TITLE
Малко помощ за функция

### ISSUE THREAD

**Issue by HristoManov91** [luchob/softuni-sept-2021-misc#74]
#40  Прикачвам тук и предната част от разговора.Успях да си направя динамичен брой полета с Product,но така и не успях да разбера как със select да добавя елементи в списъка.Видях на колегите решенията с Input но не можах да ги имплементирам за мен както е нужно със select опцията.Ако може да ми помогнеш с това,че това си е най-важната фукция в сайта и без нея е безмислен...Не съм учил за момента JS само каквото за проекта из интернет ровя както и за html и css
Иии 2рият ми проблем е че не мога от StoreResultController RestController-a да си изкарам резултата в таблица,изкарвам го със json има файл html който искам да използвам store-results.html,но не мога да изкарам да видя тази таблица дори и без данни...

**Comment by felin-dev** [comment]
Здравей, ако искаш свържи се с мен в Facebook - Simeon Stanislavov Balabanov и ще направя каквото мога за да ти помогна. 
Поздрави Симеон.

**Comment by luchob** [comment]
Привет, доколкото разбирам... Абе Javascript-a ти е леко проблемен :-)
Ами, за да не пиша целия проект (не че няма да се изкефя, но замина и неделята :-))) ) направих едно малко примерно скриптче. 

https://stackblitz.com/edit/jquery-yexb3h?file=index.html

Имаш дропдаун, бутон add, който ти добавя инпут във формата. Би трябвало да е основа, която ти върши работа.

Относно втория ти въпрос, разбирам го като "как да взема JSON през рест и да го визуализирам в таблица". Правили сме го с книжките. Виж тук -> https://github.com/luchob/softuni-sept-2021-misc/blob/master/books/src/main/resources/static/app.js

Поздрави,
Л.

**Comment by HristoManov91** [comment]
Отностно първото много благодаря,отностно 2рия въпрос ми дава тази грешка а не виждам къде е?
![image](https://user-images.githubusercontent.com/73854367/143777821-16fabe94-da05-4b78-90ba-997b19ac7776.png)

**Comment by luchob** [comment]
Никакъв шанс да разбера от този скрийншот :-) Допускам, че резултата в fetch не е JSON а е HTML, започващ, разбира се с <. Което значи, че най вероятно HTTP заявката свършва с код 302/401/403/404 или 500. Трябва да провериш в network tab-a за да разбереш повече детайли.

**Comment by HristoManov91** [comment]
![Екранна снимка 2021-11-28 232331](https://user-images.githubusercontent.com/73854367/143786521-43edb878-4236-41b6-ab8d-6a34a83c4536.png)
Всички заявки излизат с код 200...

**Comment by luchob** [comment]
Като гледам вече фазата е логване в конзола (при това работи), така че допускам че проблема вече е решен... :-)


<img width="665" alt="Screenshot 2021-11-29 at 17 12 35" src="https://user-images.githubusercontent.com/10339738/143893175-79e7db2e-62b2-4f9b-8fff-4cb498c83c70.png">

**Comment by HristoManov91** [comment]
Да проработи,благодаря.Само да попитам понеже явно нещо съм изпуснал в лекциите.Искам да имам една страница с 2 форми за дати и като избере потребителя 2 дати на съшата страница отдоло да му се появи таблица с резултати,но нещо не мога да се справя.Как трябва да стане с @ModelAttribute или Redirect attribute Или нещо друго трябва да използвам?

**Comment by luchob** [comment]
Ако ползваш REST + fetch е достатъчно като избере двете дати, да направиш GET request с два куери параметъра нещо от сорта на http://localhost:8080/my/data/endpoint?from=2021-11-01&to=2021-12-01 На респонс опълваш табличката с помощта на Javascript.

**Comment by HristoManov91** [comment]
А ако го правя с Controller само ?

**Comment by luchob** [comment]
Ами тогава можеш да направиш една HTML форма с GET метод. Това е най-доброто решение, защото GET е правилния HTTP глагол за тази цел. Още по-якото е, че линка, който се образува може да се Copy&Paste, да се буукмарква и т.н., което е много яко. Той пак ще изглежда по подобен начин.

В по-редки случаи може да се ползва POST метод, ако е много сложна сърч формата и най-вече има очакване URL-то при гет да е твърде дълго. Но това трябва да се избягва, доколкото е възможно, защото GET request-a е по-правилния начин.

**Comment by HristoManov91** [comment]
Ахаам значи с 2 get да го направя,че нещо пробвах с get И post ама не ми се получи...мерси пак за всичко

**Comment by luchob** [comment]
Бих казал ако е възможно - една форма, с две дати. 1 GET request с 2 query parameters :-)

Поздрави,
Л.

**Comment by HristoManov91** [comment]
Да де това имах предвид :D
