### ISSUE TITLE
Question about schedulers

### ISSUE THREAD

**Issue by vladikata2535** [luchob/softuni-sept-2021-misc#75]
Здрасти Лъчо, 

Имам проблем с един от scheduler-ите. Бях ти писал за едни купони, които искам да добавя към всеки user през определено време, написал съм си логиката, обаче не иска да persist-ва в репото на user-ите нови купони а прави в конзолата само select заявки и не знам защо се получава така. Можеш ли да метнеш едно око. 

https://github.com/vladikata2535/device-shop/blob/master/src/main/java/computer/shop/service/tasks/CouponsManagementScheduler.java

https://github.com/vladikata2535/device-shop/blob/eec87cfeabaddb57da68c6af4f9449acda039d0b/src/main/java/computer/shop/service/impl/CouponServiceImpl.java#L41

**Comment by luchob** [comment]
Здрасти, Влади!

Получава се така, защото никъде няма `repository.save(..)` :-)

Поздрави,
Л.
