### ISSUE TITLE
Problem with EditProfile page

### ISSUE THREAD

**Issue by TsvetomirN1** [luchob/softuni-sept-2021-misc#76]
здравейте логнал съм се и искам да си променя детайлите примерно firstname lastname като съм си направил контролер който инжектира @AuthenticationPrincipal но постоянно гърми какъв е правилния начин опитах и със сетване на полетата в userdetails но пак нестава

**Comment by luchob** [comment]
Здрасти!

Може ли да хвърля едно очо на проекта за да се ориентирам? Така ми е малко трудно да отговоря - засега разбрах, че нещо гърми при ъпдейт на юзър :P 

Поздрави,
Л.

**Comment by TsvetomirN1** [comment]
здравейте линквам временния проект https://easyupload.io/onydrv

**Comment by TsvetomirN1** [comment]
Здравейte моя грешка ето я последната версия немога да update логнатия user https://github.com/TsvetomirN1/finalProjectt разгледайте контролера и security folder някъде греша не ми намира id-to

**Comment by luchob** [comment]
Привет!

С анотацията `@AuthenticatedPrincipal` можеш да инжектираш това, което си върнал от твоя собствен `UserDetailsServiceImpl` - а именно инстанс на `UserDetails`. Например:

```
@AuthenticationPrincipal UserDetails loggedUser
```

От този обект можеш да вземеш `username`-а на логнатия юзър, а оттам, чрез сървис да вземеш направиш един view и binding модел на юзъра. Този модел може да се използва за да популираш формата на профила.

При пост заявката за ъпдейт може отново да ползваш `AuthenticationPrincipal`за да намериш user entity-то в базата и да го ъпдейтнеш (това трябва да се случи в сървис лейъра, а не в контролера).

Като цяло е напълно аналогично с update-a на offer в mobilele, само че вместо offerId получаваш user name на практика. Това е всичко, но трябва да попреправиш това което има в момента значително :)

Поздрави,
Л.

**Comment by TsvetomirN1** [comment]
благодаря за изчерпателния отговор ще го мъча without struggle there is no progress
