### ISSUE TITLE
Dynamic information in the header

### ISSUE THREAD

**Issue by felin-dev** [luchob/softuni-sept-2021-misc#77]
Здравей Лъчо, мислех си, ако може да добавя глобален модел за всички контролери и да взимам информацията от там. Само че там, където се ъпдейтва информацията стават няколко операции и страницата се ъпдейтва само с js за да не се релоадва и взима информация от рест апи-то. Мислех си да сложа js скрипт, който да се грижи за тази работа и там където се обновявва информацията да го импортна в js файловете и да извикам рест заявка за да го обновя.

**Comment by luchob** [comment]
Здрасти!

Доколкото разбирам - мисля, че комбинация от глобален модел + JS на конкретната страница, ще свърши работа.

Поздрави,
Л.
