### ISSUE TITLE
Question about auto refreshing pages

### ISSUE THREAD

**Issue by vladikata2535** [luchob/softuni-sept-2021-misc#78]
Здрасти Лъчо,

Искам да направя така че една страница(view) като се промени информацията на нея веднага да се рефрешне автоматично, за да се визуализира новата информация. Как трябва да стане това горе долу. Чрез контролерите ли или трябва да се направи нещо в JS?

Поздрави,
Влади

**Comment by luchob** [comment]
Здрасти, Влади!

Зависи от това какъв use case имаш.

1. Ако е просто някакво поле и си нацвъкал порядъчно количество JS, опитай да я обновиш с JS.
2. Ако информацията се променя на сървъра (например някой шедюлър прави нещо, или пък юзър ти прати съобщение) пробвай с "polling" - периодично изпращане на заявки (напр REST през JS) и ако нещо ново има, то правиш това от стъпка 1 :-)
3. Ако информацията е почти статична и промяната е рядка - можеш да преминеш към най-лошия вариант, а именно refresh на страницата.

Стъпка 3 е най лесна и най-непопулярна :-) Ако ползваш framework като Angular, например нещата са доста по рафинирани от горните варианти :-)

Поздрави,
Л.
