### ISSUE TITLE
Въпрос относно обновяване на информация в обект, който разширява User класа

### ISSUE THREAD

**Issue by FreshyMc** [luchob/softuni-sept-2021-misc#79]
Здравей Лъчо!
Имам следният проблем в обекта InstamarketUser попълвам при логин няколко полета като userFullname и profilePicture проблема е с второто поле, защото когато потребител смени профилната си снимка самото поле не мога да го обновя защото не е Bean и не мога да го инжектирам в UserServiceImpl класа. Та въпроса е как да стане работата, не знам дали е удачно да се декларира като Bean.
Поздрави!

**Comment by luchob** [comment]
Здрасти!

Разбира се, че не е необходимо да сложиш картинката в `InstamarketUser`. Напълно ок е, да ги сложиш в модела, който се визуализира когато се отвори профила. Както във всеки един най-обикновен контролер (напр. mobilele - показване на обява, няма разлика).

Поздрави,
Л.
