### ISSUE TITLE
Проблем с извличането на данни от фронтенда. 

### ISSUE THREAD

**Issue by Polina-MD80** [luchob/softuni-sept-2021-misc#80]
Здравейте, 
почти съм се отказала от предаването на проекта (сбърках с подредбата на курсовете от пътеката), но все  още има малко време поне да се опитам с ваша помощ да заработи и добавянето в кошницата.
На index.html, имам неща, които искам да добавя в кошницата на логнатия., Тея неща в кошницата си имат и quatity, съответно има и една цъкалка на index.html, която показва, колко от тея неща искам да добавя с бутона Order Now.
Опитах с един преписан скрипт, но не става, или 403 или 404 грешки получавах в зависимост от линковете в head часта, 
та сега се опитвам с бутона с th:action (ако хардкорна quantity = 8 напр. си добавя 8 неща в кошницата) да свърша тая табота, но **не мога да подам quantity параметъра от цъкалката**.(ако хардкорна quantity = 8 напр. си добавя 8 неща в кошницата, т.е. контролера си работи вярно)
Може ли малко помощ от вас или колегите?
За по лесно се логнете с username: admin, password: admin. Има някаква дата по таблиците.
пс: **toString() na index.html, ми изяжда новите редове**, а в обекта си го изписва както трябва ?..
https://github.com/Polina-MD80/Restaurant-Food-Ordering-Spring-Project

**Comment by luchob** [comment]
Привет Поли!

Ама ако ще се отказваш заради цъкалката, отказа не се приема ;-) Дай да я оправим тая цъкалка. Това, което ти предлагам е следното.

Първо нека да променим формата мъничко:

```
                    <form th:action="@{/cart/add/{iid}/(iid=${i.id})}" th:method="post">
                        <input th:id="${'qty'+i.id}" th:name="qty" th:value="1" type="hidden"/>
                        <input id="buttonAddToCart" type="submit" class="btn btn-primary" value="Order Now"/>
                    </form>
```
Тук добавих едно скрито поле с име `qty`, първоначална стойност 1 и `id` равно на конкатенацията `qty` и `id` на айтъма. Разкарах куантитито като path parameter, защото не ми се вижда ок да се предава така. Добре, това е по формата. След това отиваме в контролера и той изглежда вече така:

```
    @PostMapping("/cart/add/{iid}")
    public String addToCart(@PathVariable("iid") Long itemId,
        @RequestParam("qty") Integer quantity,
        @AuthenticationPrincipal RestaurantUser user)
```

Тук `qty` се променя от path variable на `RequestParam` идещ от формата от стъпка 1. Нищо особено отново. Забележи обаче, че съм го махнал от стойността в анотацията.

На последната стъпка искам да пипна малко javascript-a ти, в който изчисляваш `quantity`. Правя две малки промени, а именно:

На минус бутона:

```
if (newQuantity > 0) {
            quantityInput.val(newQuantity);
            $("#qty" + itemId).val(newQuantity);
        } else {
            showWarningModal('Minimum quantity is 1');
        }
```

На плюс бутона:
```
if (newQuantity <= 10) {
            quantityInput.val(newQuantity);
            $("#qty" + itemId).val(newQuantity);
        } else {
            showWarningModal('Maximum quantity is 5');
        }
```

Новото е, реда в който задавам стойност на `hidden` полето от стъпка 1.

Накрая е редно да пуснем дебъгера и да се порадваме на резултата (полученото `quantity` на сървъра):

<img width="658" alt="Screenshot 2021-11-27 at 17 23 30" src="https://user-images.githubusercontent.com/10339738/143687201-1bf3c538-6f7d-4cc7-ad42-d8bb2a07b68c.png">
<img width="547" alt="Screenshot 2021-11-27 at 17 23 36" src="https://user-images.githubusercontent.com/10339738/143687208-3cb1d64a-f440-44dc-ac43-3d23c4af3d1f.png">


Надявам се да съм ти помогнал!

Поздрави,
Л.

**Comment by Polina-MD80** [comment]
Здравей, Лъчо.
Благодаря за съвета, работи точно както искам, но отново удрям на камък с Js-a. Сега, след като добавя в количката, искам да върна или модал или alert,, затова е и рест контролер (че трябва да има по задание).
Имам подготвен js- add_to_cart.js, рових навсякде в гугъл, но след събмит не мога да разбера как да го извикам. Или излиза на всяко зареждане ако е on click,.... или нищо не става ... :( при стоте варианта които изпробвах.
Би ли помогнал още малко?
https://github.com/Polina-MD80/Restaurant-Food-Ordering-Spring-Project

**Comment by luchob** [comment]
Леле, сто варианта... :-)

Добре де, предлагам следното.

Да сложим някакъв клас на формата, тъй като тя фигурира по няколко пъти на една страница, ето така:

```
<form
                    ...
                    th:class="orderForm"
                    th:method="post">
                    <input th:id="${'qty'+i.id}" th:name="qty" th:value="1" type="hidden"/>
                    ...
                </form>
```

След това да добавим _csrf токъна в хедъра на апа, за да е достъпен където е нужен:

```
<head th:fragment="head">
    <meta name="_csrf" th:content="${_csrf.token}"/>
    <meta name="_csrf_header" th:content="${_csrf.headerName}"/>
    ....
```

Да не забравим да добавим твоя JS в `foods.html`.

```
<script type="text/javascript" th:src="@{/js/add_to_cart.js}"></script>
```

И накрая да напишем набързо самия скрипт:

```
// CSRF tokens
const csrfHeaderName = document.head.querySelector('[name="_csrf_header"]').content;
const csrfHeaderValue = document.head.querySelector('[name="_csrf"]').content;

// All add to cart forms
const addToCartButtons = document.querySelectorAll('.orderForm')

// intercept any of these forms
addToCartButtons.forEach(function(currentBtn){
    currentBtn.addEventListener('submit', handleAddToCart)
})

// add to cart
async function handleAddToCart(event) {
    // do not submit the form
    event.preventDefault();

    const form = event.currentTarget;
    // url 
    const url = form.action;
    // form data
    const formData = new FormData(form);
    const plainFormData = Object.fromEntries(formData.entries());
    const formDataAsJSONString = JSON.stringify(plainFormData);

    // prepare the POST request
    const fetchOptions = {
        [csrfHeaderName] : csrfHeaderValue,
        method: "POST",
        headers: {
            [csrfHeaderName] : csrfHeaderValue,
            "Content-Type" : "application/json",
            "Accept" :"application/json"
        },
        body: formDataAsJSONString
    }

    // FETCH it!
    const response = await fetch(url, fetchOptions);

    if (!response.ok) {
        // handle the error here
        throw new Error(errorMessage);
    }

    // Show the happy news
    showModalDialog("Shopping Cart", "You added the item to your cart!");

}
```

:-)

**Comment by Polina-MD80** [comment]
Благодаря, Лъчо, но и така не става(400). Но резервния ми вариант си работи,  просто няма да е рест контролер и така.. Модалите  ще ги вадя след още 2 курса :)

**Comment by luchob** [comment]
Привет!

Не става, защото в контролера трябва да имаш някакъв модел, който да се мапва с request body-то, което идва в JSON формат. Защо това не става може да се види, като видиш какво минава по мрежата, какъв ексепшън се логва на сървъра и какви са аргументите в контролера. Мисля, че си доста близко :-)

Поздрави,
Л.
