### ISSUE TITLE
code 404 for Locale-en-US.json

### ISSUE THREAD

**Issue by rsolakov** [luchob/softuni-sept-2021-misc#81]
Здрасти, Лъчо. Когато опитвам да събмитна нова обява не се получава нищо, при инспект ми дава код 404 на Locale-en-US.json? Не съм срещал подобен проблем. Защо се получава така?

**Comment by luchob** [comment]
:-) Здравей! Това за кой проект става въпрос? mobilele или нещо друго? Ако е първото сега го тествах и си се събмитва всичко както трябва. Как да го пресъздам? 

Поздрави,
Л.

**Comment by rsolakov** [comment]
За мобилеле, да. Същото е при ъпдейта. Явно проблемът е в някоя настройка щом при теб върви.

**Comment by luchob** [comment]
Привет! 

Не съм сигурен как става това при теб. Сега го тествах и с централното репо, и с твоя форк също. Не мога да пресъздам такъв проблем, нито ми хрумва защо може да се получи. Със сигурност не е въпрос на настройка, защото няма причини да пусне такава заявка. Да не би да си си играл с него локално? Ако пуснеш команда `git status`би трябвало да ти покаже локалните промени. Иначе пак - не знам какво може да е...


Поздрави,
Л.
