### ISSUE TITLE
Unit Testing/Mocking

### ISSUE THREAD

**Issue by Vellani** [luchob/softuni-sept-2021-misc#82]
Здравей, 
Имам следния казус
 ```
@BeforeEach
    void init() {
        userService = new UserServiceImpl(
                mockedUserRepository,
                new ModelMapper(),
                new Pbkdf2PasswordEncoder(),
                userRoleUtil,
                new Gson());
```
Проблемът е, че моя modelMaper, идващ от реалния Bean, има custom converters и други логики в него. Също така този "userRoleUtil" е мой си custom class, с който съм се улеснил в цялия проект и го използвам на всякъде, а тук специално търси роля в базата и я сетва на юзъра. Мисля, че вече разбираш какво ще попитам. Как да се мокне правилно? Защото, стигайки до методите на класа, и нямайки реално-вдигната база, класът не работи. За целите написах и 

`Mockito.when(userRoleUtil.setUserRole()).thenReturn(Set.of(new UserRoleEntity().setRole(UserRolesEnum.USER)));`

Където този метод `.setUserRole()` е сътветно 2-рото причастие на ексепшъни, а си мислих, че казвайки какво да ми даде ако стигне до този метод, той ще бъде реално скипнат... уви не работи така.

2-ри мини въпрос:
Какъв е смисъла реално на Mockito.when().thenReturn() при положение, че ние си казваме какво да ни върне, а в assert си сетваме какво реално ще върне... как тестваме дали правилно се запазва в базата ... не знам. Така ми изглежда сякаш минаваме само по кода, за да разберем дали въобще работи без да хвърля грешка, а резултатът е без значение

Благодаря за отделеното време!

PS. Първият въпрос е за регистрацията на user, така че е сръвнително прост. Интересно ще е, когато трябва да тествам "сложните" методи на това и други сървизи

**Comment by luchob** [comment]
Здрасти!

Добре де, нека видим как би могъл да изглежда метода за регистрацията на юзър-а (ще му подам директно сървис модел, както сме говорили) и какво може да се тества вътре.

```
   @Override
    public void registerNewUser(UserServiceModel userServiceModel) {

        UserEntity finalNewUser = modelMapper.map(userServiceModel, UserEntity.class);

        finalNewUser.setPassword(passwordEncoder.encode(userServiceModel.getPassword()));
        finalNewUser.setRoles(userRoleUtil.setUserRole());

        userRepository.save(finalNewUser);
    }
```

 Ами това, което реално може (или искаме) да тестваме тук е:

1. Че се създава някакво юзър ентити
2. Че му се сетва правилна парола, като се ползва password encoder-a, който му е подаден като депендънси
3. Че новото ентити се записва с помощта на `userRepository`, а дали този запис е успешен не ни интересува.
4. Че ролите на юзъра са именно тези, които са дошли от `userRoleUtil` а не си ги е измислил някой вътре в сървиса

Това, което НЕ искаме да тестваме е:
1. Че има връзка с базата
2. Че нещо ще се записва реално в базата (това си е отговорност на Spring Data, а в нашия Unit не ни интересува дали Spring Data работи правилно или не). Освен това, ако се замислиш може да си направиш такова UserRepository, дето въобще не работи с база, може да си записва юзърите и в текстов файл. Не че ще направиш такова нещо :), но би могъл.

Ето така си представям теста:

```
 @Test
    void testRegister() {

        // Arrange
        String testPwd = "topsecret";
        String encodedPwd = "tercespot";

        UserServiceModel testModel = new UserServiceModel();
        testModel.setPassword(testPwd);
        UserEntity testUser = new UserEntity();
        UserRoleEntity userRoleEntity = new UserRoleEntity();

        Mockito.when(mockMapper.map(testModel, UserEntity.class)).thenReturn(testUser);
        Mockito.when(mockPasswordEncoder.encode(testModel.getPassword())).thenReturn(encodedPwd);
        Mockito.when(mockUserRoleUtil.setUserRole()).thenReturn(Set.of(userRoleEntity));

        // act
        userService.registerNewUser(testModel);

        // assert
        Assertions.assertEquals(encodedPwd, testUser.getPassword()); // че паролата е правилно енкодната
        Assertions.assertEquals(Set.of(userRoleEntity), Set.of(userRoleEntity)); // че ролите са взети правилно
        Mockito.verify(mockedUserRepository).save(testUser); // че е записан юзъра
    }
```

Сега... сигурен съм, че ти е направило впечатление, че е доста тегаво да се тества някакъв по-"сериозен" компонент (с 5000 мапъри и модели и джуркане от пусто в празно). В момента, когато усетим такава тегавина имаме два варианта:

1. Да разбием сериозния метод на функционалности, които са изнесени в други компоненти, които от своя страна е по-лесно да се изтестват
2. Да се изкушим и да си напишем интегрейшън тест :-) (така се получава т.нар. "обърната" тестова пирамида) :-)

На въпроса - как тестваме дали правилно се е записало и върнало нещо от базата данни.

1. В повечето случаи това не ни интересува, защото процесът по сериализиране на нещо в ДБ е функционалност от Спринг Дейта и в нашето приложение не ни интересува дали това става правилно или не. За това се грижат тестовете в самия проект Spring Data
2. В някои случаи наистина има по сложни куерита, които бихме искали да проверим. Там може да се справим единствено с интеграционен тест.

Тъй.... малко философски отговор, ама все пак... :-)

Поздрави,
Л.

**Comment by Vellani** [comment]
Доста изчерпателно, благодаря за отговора :) и само един бърз follow-up.

Голяма част от тестовете на web-частите, автоматично покриват и service-частите ... какво правим ? 
`addPlaceholder(), registerPlaceholder()`, etc - те участват в интеграционни проверки и съм проверил дали базата се е увеличила с определен размер, обаче липсва дали правилно са запазени данните в базата, което каза, че не е моя работа, а на Spring data. Има ли смисъл да повтарям coverage-a (където спринг си оцветява в зелено) на редовете код ( защото доста вече са зелени всички) ?

**Comment by luchob** [comment]
Хммм... кво правим... ами... 60% ковиридж, такова е заданието :-)
Самият процес на запис в базата не е нужно да се тества. По скоро ако правиж интеграционен тест е хубаво да се пусне нещо през контролера и после да се провери дали е в ДБ. Ако са над 60% зелени и имаш unit test + integration test си готов.

Поздрави,
Л.
