### ISSUE TITLE
Integration test issue

### ISSUE THREAD

**Issue by Alexander-Gruev** [luchob/softuni-sept-2021-misc#83]
Здравейте, имам тестов клас OrderControllerTest, който не работи. В моя проект аз използвам клас, който екстендва Спринговския User - FitshopUser. В него имам custom поле - experienceLevel. Според този experienceLevel в навигацията на приложението показвам различна страница. Получавам следната грешка в OrderControllerTest - Property or field 'experienceLevel' cannot be found on object of type 'org.springframework.security.core.userdetails.User'. Въпросът ми е как мога да укажа на Spring да използва един FitshopUser за тестовете, който има това поле experienceLevel?

https://github.com/Alexander-Gruev/Fitshop

**Comment by luchob** [comment]
Здрасти, Алекс!

Точка 11.4 върши ли работа? https://docs.spring.io/spring-security/site/docs/4.2.x/reference/html/test-method.html

Поздрави,
Л.

**Comment by Alexander-Gruev** [comment]
За жалост @WithUserDetails(value = "username") не работи, хвърля тази грешка: Unable to create SecurityContext using @org.springframework.security.test.context.support.WithUserDetails(setupBefore=TEST_METHOD, userDetailsServiceBeanName=, value=username)

**Comment by luchob** [comment]
:-)) Да, сетих се, това е една спринг мотичка.

Причината е, че `WithUserDetails` се мъчи да дръпне юзъра преди изпълнението на `BeforeEach`. Ако се загледаш в стек трейса по надолу:

```
Caused by: org.springframework.security.core.userdetails.UsernameNotFoundException: User with name username not found
	at com.example.fitshop.service.impl.FitshopUserServiceImpl.lambda$loadUserByUsername$0(FitshopUserServiceImpl.java:32) ~[classes/:na]
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[na:na]
```

Оттук идва и нуждата от хакове, за да се заобиколи това. Виж тук:
https://stackoverflow.com/questions/42466954/spring-security-junit-withuserdetails-for-user-created-in-before

Вариант е и да го направиш с `PostConstruct` или да експоузнеш тестов UserDetailService, като последното не съм го правил... 

Тъпо е малко, ама.... Мотика :-) Пиши, ако не можеш да се справиш! Щях да го разцъкам по-подробно, ама ще ми идват на гости в 19:00 и още не съм охладил халбите :)))

Поздрави,
Л.

**Comment by Alexander-Gruev** [comment]
С @PostConstruct вместо @BeforeEach тестът минава. Благодаря ти за отделеното време и наздраве!
