### ISSUE TITLE
Integration Test RestController empty comments

### ISSUE THREAD

**Issue by yavorhr** [luchob/softuni-sept-2021-misc#84]
Здрасти, Лъчо!

Блъскам си главата с Integration-а върху Rest Controllera. Каквото и да правя, коментарите не се set-ват и изпращам празно body в get заявката. Видях от лекцията за тестовете, че при теб проблемът се оправи като настрои Entity-тата и връзките между тях, направих същото, но уви продължавам да изпитвам същата грешка..

Ако имаш време да удариш едно рамо, ще съм много благодарен 👍 

https://github.com/yavorhr/adoptDontShop

java.lang.AssertionError: JSON path "$"
Expected: a collection with size <2>
     but: collection size was <0>

**Comment by luchob** [comment]
Хей, здрасти!

Инициализирай и другата страна на релацията :-) Имам предвид това:

```
        ...
        comment1.setDog(testDog);
        ....
        comment2.setDog(testDog);
```

В метода `initDog`. 

Поздрави,
Л.
