### ISSUE TITLE
Проблем с валидацията

### ISSUE THREAD

**Issue by mitko3009** [luchob/softuni-sept-2021-misc#85]
Здрасти Лъчо. Да правиш Spring проект изглежда е като да ремонтираш кола... Едно оправиш две други се счупят. Този път филма е следния: При добавяне на нов лаптоп или компютър в базата валидацията на binding моделите не сработва. Бих се радвал професионалното си око ако надникне под капака и да каже диагноза защо така се получава. Благодаря предварително.
[Project.zip](https://github.com/luchob/softuni-sept-2021-misc/files/7625659/Project.zip)

**Comment by luchob** [comment]
Кво става, Митко :-) 

Май ще се ядосаш, като разбереш защо е този проблем :-)) Тя валидацията си работи съвсем коректно, ето:

<img width="595" alt="Screenshot 2021-11-30 at 14 52 14" src="https://user-images.githubusercontent.com/10339738/144051005-53f71188-5feb-4f10-b0d7-0459c898d459.png">

Обаче не виждам един `return` към страницата, дето ще покаже грешките :-))) Например:

```
if (bindingResult.hasErrors()) {
            redirectAttributes.addFlashAttribute("offerAddBindModel", offerAddBindModel)
                    .addFlashAttribute("org.springframework.validation.BindingResult.offerAddBindModel", bindingResult)
                    .addFlashAttribute("brandsModels", brandService.getAllBrands());
            return "redirect:/offers/add";
        }
```

Поздрави,
Л.

**Comment by mitko3009** [comment]
Новобранска работа....Благодаря ти Лъчо поздрави и на теб!
