### ISSUE TITLE
Integration test ? 

### ISSUE THREAD

**Issue by MarioVladimirov** [luchob/softuni-sept-2021-misc#86]
Здравей , ще може ли да ми помогнеш ,че не мога да разбера от къде идва грешката . 
Като стартирам теста : CommentRestControllerTest ми дава грешка в депендансито , а съм сложил всички :) Изобщо не стига до тестването . Преди това да стане ми тръгваше теста , но всичките репозиторъри бяха null и не ги разпознваше . 

https://github.com/MarioVladimirov/arsenalFinalProject

Много благодаря

**Comment by luchob** [comment]
Здравей!

Ми... в този твой проект няма такъв тест (CommentRestControllerTest) :-)

https://github.com/MarioVladimirov/arsenalFinalProject/tree/master/src/test/java/com/example/arsenalfinalproject

:-)

**Comment by luchob** [comment]
Привет!

Тук вината е моя, защото не го обясних това и много от вас сега имат подобен проблем. Ето решен абсолютно същия казус при колежката - https://github.com/luchob/softuni-sept-2021-misc/issues/87

Надявам се да помогне.

Поздрави,
Л.

**Comment by MarioVladimirov** [comment]
Извиянваме се , но пак дава грешка : Server returned unexpected status code - 401 - {"error":{"message":"cloud_name is disabled"}} като запиша в yml-то :
 cloudinary:
  cloud-name: test
  api-key: test
  api-secret: test
а когато е с паролата и Username на cloudinary Server returned unexpected status code - 401 - {"error":{"message":"Invalid Signature

**Comment by luchob** [comment]
Здравей!

Това е защото, когато вдигаш котекста се изпълнява и DBInit-a.... А той, от своя страна се опитва да катери нещо в cloudinary. Като решение може да ти предложа, например, да използваш `ConditionalOnProperty` анотация. Например, в истинското `application.yaml` може да има пропърти environment със стойност `prd`, а в тестовото същото пропърти да има стойност `tst`. Тогава може да се анотира `DBInit` по следният начин:

```
@Component
@ConditionalOnProperty(name = "environment", havingValue = "prd")
public class DBInit implements CommandLineRunner
```

Поздрави,
Л.

**Comment by MarioVladimirov** [comment]
стана така  Благодаря . Сложиж анотацията и в yml файла написах environment: prd , а в другия файл environment: test
По този начин не минава през cloudinary-то ли ?

**Comment by luchob** [comment]
... Не :-) По този начин класът DBInit не се регистрира в application context-a на спринг и съответно това което е вътре не се изпълнява.

Поздрави,
Л.

**Comment by MarioVladimirov** [comment]
Здравей , пак съм аз :) (вече ти писна от мене ) 
Опитвам се да си тествам productControllera метода add и трябва да сложa multipartfile 
 MockMultipartFile image2 = new MockMultipartFile("logo", " logo","image/jpeg" , "src/main/resources/static/images/logo.png".getBytes() );
 
mockMvc
                .perform(MockMvcRequestBuilders.multipart("/product/add")
                        .file("picture" , log.getBytes())

мисля ,че така трябва да е . Изрвох нета да гледам и нищо не става ... (сигурно трябва още да ровя :) )
и ми дава грешка на теста когато качва снимката в clouda  401 - {"error":{"message":"cloud_name is disabled"}}

много ще съм благодарен ако удариш едно рамо :)
