### ISSUE TITLE
POST request  return 403

### ISSUE THREAD

**Issue by ViliqnVachev** [luchob/softuni-sept-2021-misc#89]
Здравейте, имам проблем с добавянето на коментар през rest controller. Използвам fetch, за да направя post request към съответния ресуср, но ми връща 403
https://github.com/ViliqnVachev/movie-library

**Comment by luchob** [comment]
Здравей!

Проблемът е в липсата на CSRF тоукън във фетч заявката. Това го "отработихме" вчера в една безумна JS сага :-) и е комитнато в pathfinder, където създадохме успешно коментарче. Като се замисля, с помощта на th:action може да е по-опростено дори.

Поздрави,
Л.
