### ISSUE TITLE
Cascade Issues

### ISSUE THREAD

**Issue by AlexanderAtanasov** [luchob/softuni-sept-2021-misc#90]
Здравей Лъчо,

Не мога поради някаква причина да изтрия parent и към него директно да се изтрие child-а, въпреки че тествах с 
"cascade = CascadeType.ALL", "cascade = CascadeType.REMOVE" и "orphanRemoval = true".
Parent - https://pastebin.com/Anu4qwiU
Child - https://pastebin.com/a8NY57tD

Благодаря ти предварително!

**Comment by AlexanderAtanasov** [comment]
Solved.

**Comment by Zhulbars** [comment]
Здарвей, как реши проблема? )
