### ISSUE TITLE
Проблем с интеграционни тестове

### ISSUE THREAD

**Issue by nzlateva** [luchob/softuni-sept-2021-misc#91]
Здрасти, Лъчо,

Отново проблем с интеграционните тестове :(
До преди да създам AuthorControllerTest останалите 2 работеха. Сега обаче който и интеграцинен тест да рънна, получавам грешка, че нямам bean of type 'org.springframework.security.crypto.password.PasswordEncoder'.
Трябва ли да се дефинира допълнителна конфигурация и ако да, къде?
https://github.com/nzlateva/WebBookstore 
Поздрави,
Н.

**Comment by luchob** [comment]
Здрасти, Н!

Всъщност - не знам :-) Когато направиш `push` на `AuthorControllerTest` в github ще го погледна и ще ти кажа :-) В момента все още го няма там.

Поздрави,
Л.

**Comment by nzlateva** [comment]
Упс. Вече е в github. :))

**Comment by luchob** [comment]
Твърдо и категорично не виждам такъв ексепшън свързан с `PasswordEncoder`, но виждам доста други от типа:

```
org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.TransientPropertyValueException: Not-null property references a transient value - transient instance must be saved before current operation : bg.softuni.webbookstore.model.entity.BookEntity.creator -> bg.softuni.webbookstore.model.entity.UserEntity; nested exception is java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: Not-null property references a transient value - transient instance must be saved before current operation : bg.softuni.webbookstore.model.entity.BookEntity.creator -> bg.softuni.webbookstore.model.entity.UserEntity
```

В тези случаи, понеше нямаш каскадност на операцията, хибернейт ти иска да запишеш user entity-то в ДБ преди да го сложиш в буук ентитито. Защо - защото като тръгне да записва book иска да направи един select за да си дръпне юзъра и тогава се оказва, че този юзър няма "persistent context". Като оправиш около 6-7 такива грешки, вече теста работи. Но, ако го пуснеш заедно с другите тестове пак се чупи, този път защото:

```
.perform(get("/authors/1"))
```

завършва с 404. Просто защото споделяш една база с останалите тестове и най-вероятно твоя тестов юзър е вече с id 2, 3 или 10. Вместо това трябва да направиш:

```
.perform(get("/authors/" + testAuthor1.getId()))
```

И ей такива дреболии, като ги поправиш ще имаш добре работещ тест. 

Но все пак виждам, че си се уверила, че този тип тестове може да са доста чупливи понякога :-)

Поздрави,
Л.

**Comment by nzlateva** [comment]
Благодаря ти! :)))

**Comment by luchob** [comment]
<img width="770" alt="Screenshot 2021-12-03 at 10 54 05" src="https://user-images.githubusercontent.com/10339738/144574096-c0de16ed-4c8f-4b5e-9f55-55139f3def48.png">
