### ISSUE TITLE
Малко, проблемчета!

### ISSUE THREAD

**Issue by Nikolay-Yakimov** [luchob/softuni-sept-2021-misc#93]
Здравей, Лъчо!!

Имам проблем, с тези "тестове" имам някакъв пропуск някъде, и не знам къде е!
 Може ли да хвърлиш едно око? И по някаква причина в Коментарите ми се записва само NULL, в колоната "content", 
Помагай,че го закъсах!!! https://github.com/Nikolay-Yakimov/Home_Sport_first

**Comment by Nikolay-Yakimov** [comment]
С коментарите се оправих!!!
Но с тестовете борбата продължава!!!!

**Comment by luchob** [comment]
Хей, Ники - no pain - no gain ;-)

В репозиторито ти в гитхъб има един единствен тест и без да го пускам, знам че няма да тръгне :-) Проблемът ще е същия, както при колегата ни - виж тук -> https://github.com/luchob/softuni-sept-2021-misc/issues/87

Поздрави,
Л.

**Comment by Nikolay-Yakimov** [comment]
Боря се, имам проблем с Commit-та в Git-a; 
Благодаря за светкавичния отговор!
Няма да се предавам!
Лека вечер!!!!
