### ISSUE TITLE
this.mockMvc

### ISSUE THREAD

**Issue by Nikolay-Yakimov** [luchob/softuni-sept-2021-misc#94]
java.lang.NullPointerException: Cannot invoke "org.springframework.test.web.servlet.MockMvc.perform(org.springframework.test.web.servlet.RequestBuilder)" because "this.mockMvc" is null  - проблемът ми ! Извинявам се но това ме тормози?!

**Comment by luchob** [comment]
Привет!

За да ти помогна, трябва да push-неш теста в github. 

Иначе не е възможно :-)

Поздрави,
Л.

**Comment by luchob** [comment]
Затварям, заради липса на отговор...
