### ISSUE TITLE
Assigning Managers

### ISSUE THREAD

**Issue by MurAhm** [luchob/softuni-sept-2021-misc#95]
Здравей, Лъчо! 

Да речем, че имам магазин с някоклко локации и искам всяка от тях да има управител. Админа ли трябва да ги 'назначава' или има друг начин?

Лека вечер.

**Comment by luchob** [comment]
Добро утро!

Да, вариант е това. Един админ панел за редактиране на юзъри, защо не. Иначе вариантите варират от прости (като този с админа) до абсолютно безумни :-), в зависимост от нуждите на бизнеса и мозъка, който ги измисля :-)

Поздрави,
Л.
