### ISSUE TITLE
Въпрос относно Spring Security

### ISSUE THREAD

**Issue by FreshyMc** [luchob/softuni-sept-2021-misc#96]
Привет Лъчо!
Имам следният казус, в моето приложение има функционалност при, която админа да одобрява потребителите, които искат да станат продавачи в моята платформа. Всичко работи, но забелязах, че когато одобрен вече продавач, който е влезнал в приложението и има активна сесия може да добавя обяви дори когато админа му махне правата. Тоест искам независимо дали потребител е в приложението, когато му се махнат правата на продавач да не може да добява нови обяви и да вижда някои функционалности. Възможно ли е това да се случи. Та админската страница за одобряване на потребители за продавачи става от пътя **/admin/approve**, а за да пуснеш заявка за продавач става от **/profile/become-seller**
Линк към проекта: https://github.com/FreshyMc/InstamarketProject
Благодаря предварително! 
Лек и успешен ден!

**Comment by luchob** [comment]
Ха, това е доста интересно, честно кзано досега не съм правил такова нещо. Тези дни ще разтърся как става и ще пиша. Ама днеска утре малко почивчица, че ми дойде нагорно курса :-)) Поздрави и ще пиша.

Л.

**Comment by luchob** [comment]
Привет!

Хвърлих едно очо на документацията и ми се струва особено обещаващо т.нар. `SessionRegistry`за нашата цел.

Интересна е секцията `Querying the SessionRegistry for currently authenticated users and their sessions` [в т.10.12.6](https://docs.spring.io/spring-security/site/docs/5.2.1.RELEASE/reference/htmlsingle/#concurrent-sessions) `Concurrency Control`.

За съжаление... не, по-скоро за щастие си имам Нина у дома и тази вечер (Никулден) няма да мога да си поиграя с реализацията на това нещо, но ми изглежда доста обещаващо. Ако пробваш преди мен - пиши.

Поздрави,
Л.

**Comment by FreshyMc** [comment]
Ще го пробвам по-късно тази седмица, че имам малко работа по фийчърите, които съм наблъскал и хей най-приятното писане на тестовете :-) Но наистина като му хвърлих едно око звучи доста обещаващо. 
Поздрави!

**Comment by luchob** [comment]
Здрасти!

SessionRegistry-то не е решението което търсим, ако искаме да няма логаут, разбира се. Ако искаме да запазим ДРУГИЯ юзър логнат и да му рефрешнем привилегиите може да ползваш решението дето е описано тук: https://stackoverflow.com/questions/50585731/spring-security-how-to-change-user-roles-without-login-and-logout

Работи :-) 
Tested (TM)

Приятна вечер!

**Comment by FreshyMc** [comment]
Благодаря ти Лъчо, обаче има следния проблем това като чели сменя сесията на човека който има админския панел пред него, а не на този който е извън панела от друг таб. Ефекта който получих е, че като премахна някой от продавачите взима, че ме логва в техният профил и ме изхвърля от админския профил. Не знам може и аз нещо да съм омазал, но е по инструкциите.

**Comment by luchob** [comment]
Дааа, няма да стане така, определено. Грешен ми е теста. Може да го направим с логаутване със SessionRegistry но без logout все още не знам как да стане. Пфю... Ще поровя пак.

**Comment by FreshyMc** [comment]
Хей Лъчо, нека го направим с логаутване няма проблем за мен, важното е правата да работят коректно :-)

**Comment by luchob** [comment]
Пфю, добре! Нек пробваме тогава с логаут. Първо да регистрираме `sessionRegistry` в някоя конфикурация като bean:

```
    @Bean
    SessionRegistry sessionRegistry() {
        return new SessionRegistryImpl();
    }
```

След това настройваме някакъв сешън мениджмънт в спринг секюрити конфигурацията, като в конструктора и инджектнем `sessionRegistry`:

```
        and().
          logout().
         ...
          deleteCookies("JSESSIONID").
        and().
          sessionManagement().
          maximumSessions(-1).
          sessionRegistry(sessionRegistry).
          expiredUrl("/users/login");//where to redirect users with expired sessions
```

Самият код за логаут може би ще изглежда по подобен начин:

```
List<Object> allPrincipals = sessionRegistry.getAllPrincipals();

    allPrincipals.
        stream().
        filter(...).//filter by username/email and instance of principal here
        forEach(
        p -> {
          final List<SessionInformation> allSessions = 
              sessionRegistry.
                  getAllSessions(p, false).forEach(si -> si.expireNow());//invalidate the session of the target user
        }
    );
```

:-) Да видим :-)

**Comment by FreshyMc** [comment]
Да така работи перфектно :-) Ще споделя кода ако някой колега има интерес:
`private void logoutUser(String username){
        List<Object> allPrincipals = sessionRegistry.getAllPrincipals();

        for(Object p : allPrincipals){
            if(p instanceof InstamarketUser){
                if(((InstamarketUser) p).getUsername().equals(username)){
                    sessionRegistry.getAllSessions(p, false).stream().forEach(s -> {
                        s.expireNow();
                    });
                }
            }
        }
    }`
Въртя го без stream api защото ми се видя по-простичко.
