### ISSUE TITLE
Cloudinary issue : Must supply cloud_name in tag or in configuration

### ISSUE THREAD

**Issue by yavorhr** [luchob/softuni-sept-2021-misc#97]
Здрасти Лъчо!
Опитвам се да си интегрирам Cloudinary за смяна на снимка на User в profile. 
Грешката, която получавам  : Must supply cloud_name in tag or in configuration, явно имам някакъв проблем с cloud_name в конфигурацията, но всичко ми изглежда окей и не намирам проблемът. 
Правя всичко както в нашия проект, с разликата че изпозлвам application.properties вместо yaml.

Ако имаш възможност да хвърлиш едно око, ще съм ти както винаги много благодарен!

https://github.com/yavorhr/adoptDontShop

Поздрави,
Явор

**Comment by rd-lachezar-balev** [comment]
Привет!

Нещо копи пейст грешка ли ми се привижда или вместо:

```
spring.cloudinary=
cloudinary.api-key=: 991279857293315
cloudinary.api-secret=: ${CLOUDINARY_API_SECRET}
cloudinary.cloud-name= yavorhr
``` 

Трябва да е (вкл. без интервалите :-) ):

```
cloudinary.api-key=991279857293315
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
cloudinary.cloud-name=yavorhr
```

Поздрави,
Л.
