### ISSUE TITLE
Проекта

### ISSUE THREAD

**Issue by chaneto** [luchob/softuni-sept-2021-misc#98]
Здравей, Лъчо.
Предварително се извинявам, ако въпроса не е в твоята компентенция или не си ангажиран с такъв тип въпроси.
Може ли да ми кажеш, след качването на проекта в анкетата - 5 декември, до датата на изпита 12 - декември, може ли да се нанасят корекции по проекта и ще бъдат ли приети като краен проект за защитата.
Благодаря.

**Comment by luchob** [comment]
Бонджорно!

Доколкото бях говорил по въпроса с @chmitkov е необходимо да се качи проекта в почти завършен вид и оттам нататък може да се правят "малки" корекции. Т.е. не може да качиш празно репозитори :-) и изведнъж да го напълниш на 11-ти декември :-) Какво точно значи "малка" корекция и на мен не ми е ясно, за да си по-сигурен може да питаш съпорта на СофтУни да не стане някой сакатлък :-)

Поздрави от мен и приятен (или поне ползотворен) уикенд!
Л.
