### ISSUE TITLE
Foreign key constraint falls error

### ISSUE THREAD

**Issue by yavorhr** [luchob/softuni-sept-2021-misc#99]
Здрасти Лъчо!

Извинявам се предварително, че пиша през почивен ден!
Накратко имам следният казус : Dog and Picture entity. Dog ми е parent entity, а в Pictures пазя снимките за всяко едно куче. 
В PictureEntity съответно имам foreign_key dog_id. 
Имплементирах Cloudinary и когато се опитам да изтрия снимка от Picture entity, ми гърми с foreign key constraint error.
Сешаш ли се за някакъв work around ? Гледах за разни анотации, с които се изключва foreign key error check-a, но не сработи особено.

Поздрави,
Явор!

**Comment by luchob** [comment]
Здрасти!

Не съм сигурен как го триеш, но ето примерен код, който щракнах набързо:

```
@Override
    public void test(long dogId)  {
        Dog dog = dogRepository.findById(dogId).orElseThrow();
        List<Picture> pictures = dog.getPictures();
        if (!pictures.isEmpty()) {
            pictureRepository.delete(pictures.get(0));
        }
    }
```

Резултатът от конзолата:

```
2021-12-04 17:20:17.540 DEBUG 99053 --- [nio-8080-exec-1] org.hibernate.SQL                        : 
    delete 
    from
        pictures 
    where
        id=?
2021-12-04 17:20:17.540 TRACE 99053 --- [nio-8080-exec-1] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [BIGINT] - [28]
2
```

И ентитито на картинката изчезва от ДБ :-)

Поздрави,
Л.
